
//СУЩЕСТВИТЕЛЬНЫЕ
const words1 = [
  { german: 'die Tasse', russian: 'чашка' },
    { german: 'der Tisch', russian: 'стол' },
    { german: 'das Messer', russian: 'нож' },
    { german: 'die Straße', russian: 'улица' },
    { german: 'der Kühlschrank', russian: 'холодильник' },
    { german: 'alle', russian: 'все' },
    { german: 'die Flasche', russian: 'бутылка' },
    { german: 'der Teller', russian: 'тарелка' },
    { german: 'das Glas', russian: 'стакан' },
    { german: 'die Gabel', russian: 'вилка' },
    { german: 'der Löffel', russian: 'ложка' },
    { german: 'das Tablett', russian: 'поднос' },
    { german: 'die Suppe', russian: 'суп' },
    { german: 'der Zucker', russian: 'сахар' },
    { german: 'das Salz', russian: 'соль' },
    { german: 'der Saft', russian: 'сок' },
    { german: 'die Hose', russian: 'брюки' },
    { german: 'das Hemd', russian: 'рубашка' },
    { german: 'die Krawatte', russian: 'галстук' },
    { german: 'der Pullover', russian: 'пуловер' },
    { german: 'die Socke', russian: 'носок' },
    { german: 'der Hut', russian: 'шляпа' },
    { german: 'das Kleid', russian: 'платье' },
    { german: 'der Rock', russian: 'юбка' },
    { german: 'die Jacke', russian: 'куртка' },
    { german: 'der Knopf', russian: 'пуговица' },
    { german: 'die Mutter', russian: 'мать' },
    { german: 'der Vater', russian: 'отец' },
    { german: 'die Tante', russian: 'тётя' },
    { german: 'der Onkel', russian: 'дядя' },
    { german: 'die Tochter', russian: 'дочь' },
    { german: 'der Sohn', russian: 'сын' },
    { german: 'die Enkelin', russian: 'внучка' },
    { german: 'der Enkel', russian: 'внук' },
    { german: 'die Großmutter', russian: 'бабушка' },
    { german: 'der Großvater', russian: 'дедушка' },
    { german: 'das Bett', russian: 'кровать' },
    { german: 'der Arzt', russian: 'врач' },
    { german: 'die Ärztin', russian: 'врач (женщина)' },
    { german: 'das Krokodil', russian: 'крокодил' },
    { german: 'der Kopf', russian: 'голова' },
    { german: 'die Hand', russian: 'кисть руки' },
    { german: 'das Bein', russian: 'нога' },
    { german: 'der Hals', russian: 'шея' },
    { german: 'der Zahn', russian: 'зуб' },
    { german: 'die Nase', russian: 'нос' },
    { german: 'der Bauch', russian: 'живот' },
    { german: 'das Auge', russian: 'глаз' },
    { german: 'die Brust', russian: 'грудь' },
    { german: 'der Fuß', russian: 'стопа' },
    { german: 'die Metzgerei', russian: 'мясная лавка' },
    { german: 'die Bäckerei', russian: 'булочная' },
    { german: 'die Autowerkstatt', russian: 'автомастерская' },
    { german: 'die Post', russian: 'почта' },
    { german: 'die Reinigung', russian: 'химчистка' },
    { german: 'die Apotheke', russian: 'аптека' },
    { german: 'der Bahnhof', russian: 'вокзал' },
    { german: 'das Schwimmbad', russian: 'бассейн' },
    { german: 'das Restaurant', russian: 'ресторан' },
    { german: 'das Reisebüro', russian: 'бюро путешествий' },
    { german: 'die Polizei', russian: 'полиция' },
    { german: 'das Konto', russian: 'счёт (в банке)' },
    { german: 'der Zoll', russian: 'таможня' },
    { german: 'der Schalter', russian: 'окошечко' },
    { german: 'der Empfänger', russian: 'получатель' },
    { german: 'die Durchsage', russian: 'сообщение (радио и т.д.)' },
    { german: 'der Anrufbeantworter', russian: 'автоответчик' },
    { german: 'die Immobilie', russian: 'недвижимость' },
    { german: 'der Funkturm', russian: 'радиобашня' },
    { german: 'die Buslinie', russian: 'автобусный маршрут' },
    { german: 'das Zentrum', russian: 'центр' },
    { german: 'die Grenze', russian: 'граница' },
    { german: 'die Innenstadt', russian: 'центр города' },
    { german: 'die Schaltuhr', russian: 'недвижимость' },
    { german: 'der Backofen', russian: 'таймер' },
    { german: 'das Kochfeld', russian: 'духовка' },
    { german: 'das Gasherd', russian: 'варочная поверхность' },
    { german: 'der Seiher', russian: 'газовая плита' },
    { german: 'die Karaffe', russian: 'графин' },
    { german: 'der Trichter', russian: 'воронка' },
    { german: 'das Nudelholz', russian: 'скалка' },
    { german: 'der Dunstabzug', russian: 'вытяжка' },
    { german: 'der Dosenöffner', russian: 'консервный нож' },
    { german: 'an der Wand', russian: 'на стене' },
    { german: 'in der Garage', russian: 'в гараже' },
    { german: 'an der Decke', russian: 'на потолке' },
    { german: 'auf dem Tisch', russian: 'на столе' },
    { german: 'im Park', russian: 'в парке' },
    { german: 'am Fenster', russian: 'у окна' },
    { german: 'auf dem Balkon', russian: 'на балконе' },
    { german: 'am Strand', russian: 'на пляже' },
    { german: 'in der Wohnung', russian: 'в квартире' },
    { german: 'auf der Terrasse', russian: 'на террасе' },
    { german: 'kennen lernen A', russian: 'познакомиться с кем-л.' },
    { german: 'der Meter', russian: 'метр' },
    { german: 'der Zentimeter', russian: 'сантиметр' },
    { german: 'der Kilometer', russian: 'километр' },
    { german: 'der Liter', russian: 'литр' },
    { german: 'der Gramm', russian: 'грамм' },
    { german: 'anrufen A', russian: 'звонить (кому-л.)' },
    { german: 'der Beamte', russian: 'чиновник' },
    { german: 'anklicken', russian: 'кликать' },
    { german: 'das Handy', russian: 'моб. телефон' },
    { german: 'der Anrufbeantworter', russian: 'автоответчик' },
    { german: 'besetzt', russian: 'занято' },
    { german: 'das Internet', russian: 'интернет' },
    { german: 'schicken', russian: 'послать' },
    { german: 'weiter', russian: 'дальше' },
    { german: 'übernachten', russian: 'переночевать' },
    { german: 'wegfahren', russian: 'уезжать' },
    { german: 'wechseln', russian: 'обменивать' }
  // Добавьте здесь больше слов и переводов для массива words1
];

//СУЩЕСТВИТЕЛЬНЫЕ 2
const words2 = [
  { german: 'klettern', russian: 'взбираться' },
    { german: 'bummeln', russian: 'бродить, прогуливаться' },
    { german: 'filmen', russian: 'снимать (фильм)' },
    { german: 'zeigen', russian: 'показать' },
    { german: 'Schuhe putzen', russian: 'чистить обувь' },
    { german: 'im Bett bleiben', russian: 'оставаться в постели' },
    { german: 'den Knopf annähen', russian: 'пришить пуговицу' },
    { german: 'mit dem Auto', russian: 'на автомобиле' },
    { german: 'der Gasthof', russian: 'гостиница (небольшая)' },
    { german: 'die Brücke', russian: 'мост' },
    { german: 'vor allem', russian: 'прежде всего' },
    { german: 'tief', russian: 'глубоко' },
    { german: 'breit', russian: 'широко' },
    { german: 'zu Fuß', russian: 'пешком' },
    { german: 'die Kneipe', russian: 'кабак' },
    { german: 'besichtigen', russian: 'осматривать' },
    { german: 'die Hauptstadt', russian: 'столица' },
    { german: 'stattfinden', russian: 'состояться' },
    { german: 'der Keller', russian: 'подвал' },
    { german: 'wegfahren', russian: 'уезжать' },
    { german: 'das Regal', russian: 'полка' },
    { german: 'umziehen', russian: 'переезжать' },
    { german: 'mieten', russian: 'снимать квартиру' },
    { german: 'schmecken', russian: 'пробовать на вкус' },
    { german: 'die Treppe', russian: 'лестница' },
    { german: 'der Parkplatz', russian: 'парковочное место' },
    { german: 'die Haltestelle', russian: 'остановка' },
    { german: 'der Bus', russian: 'автобус' },
    { german: 'der Trolleybus', russian: 'троллейбус' },
    { german: 'die Straßenbahn', russian: 'трамвай' },
    { german: 'das Auto', russian: 'автомобиль' },
    { german: 'das Fahrrad', russian: 'велосипед' },
    { german: 'der Roller', russian: 'роликовые коньки / самокат' },
    { german: 'der Zug', russian: 'поезд' },
    { german: 'das Flugzeug', russian: 'самолет' },
    { german: 'der Hubschrauber', russian: 'вертолет' },
    { german: 'das Schiff', russian: 'корабль' },
    { german: 'die Spritze', russian: 'шприц' },
    { german: 'das Pflaster', russian: 'пластырь' },
    { german: 'die Salbe', russian: 'мазь' },
    { german: 'das Rezept', russian: 'рецепт (медицинский)' },
    { german: 'der Verband', russian: 'повязка / бинт' },
    { german: 'die Tropfen', russian: 'капли' },
    { german: 'das Thermometer', russian: 'термометр' },
    { german: 'die Tablette', russian: 'таблетка' },
    { german: 'die Zäpfchen', russian: 'суппозиторий' },
    { german: 'der Rollstuhl', russian: 'инвалидная коляска' },
    { german: 'das Sofa', russian: 'диван' },
    { german: 'der Sessel', russian: 'кресло' },
    { german: 'der Tisch', russian: 'стол' },
    { german: 'das Regal', russian: 'полка' },
    { german: 'das Bett', russian: 'кровать' },
    { german: 'der Schrank', russian: 'шкаф' },
    { german: 'die Kommode', russian: 'комод' },
    { german: 'der Stuhl', russian: 'стул' },
    { german: 'die Gardine', russian: 'штора' },
    { german: 'der Nachttisch', russian: 'тумбочка' },
    { german: 'das Heft', russian: 'тетрадь' },
    { german: 'das Lineal', russian: 'линейка' },
    { german: 'der Spitzer', russian: 'точилка' },
    { german: 'die Tafel', russian: 'доска (школьная)' },
    { german: 'die Kreide', russian: 'мел' },
    { german: 'der Schwamm', russian: 'губка' },
    { german: 'die Schere', russian: 'ножницы' },
    { german: 'der Radiergummi', russian: 'ластик' },
    { german: 'das Buch', russian: 'книга' },
    { german: 'der Block', russian: 'блокнот' },
    { german: 'die Vase', russian: 'ваза' },
    { german: 'die Tasche', russian: 'сумка' },
    { german: 'der Ring', russian: 'кольцо' },
    { german: 'das Parfüm', russian: 'духи' },
    { german: 'die Halskette', russian: 'ожерелье' },
    { german: 'die Pfeife', russian: 'трубка (курительная)' },
    { german: 'das Feuerzeug', russian: 'зажигалка' },
    { german: 'die Uhr', russian: 'часы' },
    { german: 'das Lächeln', russian: 'улыбка' },
    { german: 'das Geschenk', russian: 'подарок' },
    { german: 'die Wand', russian: 'стена' },
    { german: 'der Boden', russian: 'пол' },
    { german: 'das Fenster', russian: 'окно' },
    { german: 'das Zimmer', russian: 'комната' },
    { german: 'die Tür', russian: 'дверь' },
    { german: 'die Küche', russian: 'кухня' },
    { german: 'die Diele', russian: 'прихожая' },
    { german: 'der Korridor', russian: 'коридор' },
    { german: 'das Schlafzimmer', russian: 'спальня' },
    { german: 'das Gästezimmer', russian: 'гостевая комната' },
    { german: 'am ersten Januar', russian: 'первого января' },
    { german: 'im März', russian: 'в марте' },
    { german: 'gestern', russian: 'вчера' },
    { german: 'vorgestern', russian: 'позавчера' },
    { german: 'übermorgen', russian: 'послезавтра' },
    { german: 'im Winter', russian: 'зимой' },
    { german: 'im Frühling', russian: 'весной' },
    { german: 'im Sommer', russian: 'летом' },
    { german: 'im Herbst', russian: 'осенью' },
    { german: 'um 8 Uhr morgens', russian: 'в 8 часов утра' },
    { german: 'der Erwachsene', russian: 'взрослый' },
    { german: 'die Fahrkarte', russian: 'билет на проезд' },
    { german: 'das Museum', russian: 'музей' },
    { german: 'das Denkmal', russian: 'памятник' },
    { german: 'die Ecke', russian: 'угол' },
    { german: 'an der Ecke', russian: 'на углу' },
    { german: 'das Gebäude', russian: 'здание' },
    { german: 'der Fahrplan', russian: 'расписание движения' },
    { german: 'die Grenze', russian: 'граница' },
    { german: 'das Geld wechseln', russian: 'менять деньги' },
    { german: 'obligatorisch', russian: 'обязательный' },
    { german: 'mitbringen', russian: 'принести с собой' },
    { german: 'bedienen A', russian: 'обслуживать кого-л.' },
    { german: 'das Meer', russian: 'море' },
    { german: 'ordnen', russian: 'приводить в порядок' }
  // Добавьте здесь больше слов и переводов для массива words2
];

//ГЛАГОЛЫ
const words3 = [
  
  { german: 'sagen', russian: 'сказать' },
    { german: 'träumen', russian: 'мечтать' },
    { german: 'lesen', russian: 'читать' },
    { german: 'spielen', russian: 'играть' },
    { german: 'wohnen', russian: 'жить' },
    { german: 'treffen*', russian: 'встречать*' },
    { german: 'braten', russian: 'жарить' },
    { german: 'kochen', russian: 'варить' },
    { german: 'backen', russian: 'печь' },
    { german: 'salzen', russian: 'солить' },
    { german: 'schneiden', russian: 'резать' },
    { german: 'aufräumen', russian: 'убираться' },
    { german: 'putzen', russian: 'чистить' },
    { german: 'waschen', russian: 'мыть, стирать' },
    { german: 'Bestellen', russian: 'заказывать' },
    { german: 'fragen', russian: 'спрашивать' },
    { german: 'denken', russian: 'думать' },
    { german: 'besuchen', russian: 'посещать' },
    { german: 'weinen', russian: 'плакать' },
    { german: 'schreiben', russian: 'писать' },
    { german: 'buchstabieren', russian: 'по буквам' },
    { german: 'meinen', russian: 'иметь ввиду' },
    { german: 'reisen', russian: 'путешествовать' },
    { german: 'verstehen', russian: 'понимать' },
    { german: 'schreiben', russian: 'писать' },
    { german: 'verschreiben', russian: 'прописывать' },
    { german: 'sich rasieren', russian: 'бриться' },
    { german: 'sich waschen', russian: 'мыться' },
    { german: 'sich beeilen', russian: 'спешиться' },
    { german: 'sich kämmen', russian: 'чесаться' },
    { german: 'sich treffen', russian: 'встречаться' },
    { german: 'sich erinnern', russian: 'помнить' },
    { german: 'sich interessieren', russian: 'интересоваться' },
    { german: 'sich erholen', russian: 'отдыхать' },
    { german: 'sich verspäten', russian: 'опаздывать' },
    { german: 'sich freuen', russian: 'радоваться' },
    { german: 'drucken', russian: 'печатать' },
    { german: 'parken', russian: 'парковать' },
    { german: 'tragen', russian: 'носить' },
    { german: 'wecken', russian: 'будить' },
    { german: 'merken', russian: 'замечать' },
    { german: 'lachen', russian: 'смеяться' },
    { german: 'erklären', russian: 'объяснять' },
    { german: 'beraten A', russian: 'советовать кому-л.' },
    { german: 'sitzen', russian: 'сидеть' },
    { german: 'zurückrufen A', russian: 'перезвонить кому-л.' },
    { german: 'schicken', russian: 'послать' },
    { german: 'weiter', russian: 'дальше' },
    { german: 'wegfahren', russian: 'уезжать' },
    { german: 'wechseln', russian: 'обменивать' },
    { german: 'klettern', russian: 'взбираться' },
    { german: 'bummeln', russian: 'бродить, прогуливаться' },
    { german: 'filmen', russian: 'снимать (фильм)' },
    { german: 'zeigen', russian: 'показать' },
    { german: 'Schuhe putzen', russian: 'чистить обувь' },
    { german: 'im Bett bleiben', russian: 'оставаться в постели' },
    { german: 'den Knopf annähen', russian: 'пришить пуговицу' },
    { german: 'mit dem Auto', russian: 'на автомобиле' },
    { german: 'mieten', russian: 'снимать квартиру' },
    { german: 'schmecken', russian: 'пробовать на вкус' },
    { german: 'ins Theater gehen', russian: 'ходить в театр' },
    { german: 'Karten spielen', russian: 'играть в карты' },
    { german: 'Rad fahren', russian: 'ездить на велосипеде' },
    { german: 'Ski fahren', russian: 'ездить на лыжах' },
    { german: 'stricken', russian: 'вязать' },
    { german: 'wandern', russian: 'ходить в поход' },
    { german: 'fernsehen', russian: 'смотреть телевизор' },
    { german: 'Fußball spielen', russian: 'играть в футбол' },
    { german: 'shoppen gehen', russian: 'ходить по магазинам' },
    { german: 'spazieren gehen', russian: 'гулять' },
    { german: 'duschen', russian: 'принимать душ' },
    { german: 'feiern', russian: 'праздновать' },
    { german: 'frühstücken', russian: 'завтракать' }
  // Добавьте здесь больше слов и переводов для массива words3
];

//ФРАЗЫ
const words4 = [
  { german: 'Klavier spielen', russian: 'играть на пианино' },
    { german: 'normalerweise', russian: 'обычно' },
    { german: 'zu Hause', russian: 'дома' },
    { german: 'Freut mich', russian: 'Я очень рад' },
    { german: 'Sehr angenehm', russian: 'Очень приятно' },
    { german: "Wie geht's?", russian: 'Как дела?' },
    { german: 'Ich habe heute frei', russian: 'У меня сегодня выходной' },
    { german: 'Ich zahle bar', russian: 'Я плачу наличными' },
    { german: 'Das macht Spaß', russian: 'Это доставляет удовольствие' },
    { german: 'Ich bin dran', russian: 'Моя очередь' },
    { german: 'Ich vermisse dich', russian: 'Я по тебе скучаю' },
    { german: 'Melde dich', russian: 'Не пропадай!' },
    { german: 'nach 2 Stunden', russian: 'через 2 часа' },
    { german: 'vor 5 Minuten', russian: '5 минут назад' },
    { german: 'im Jahr', russian: 'в году' },
    { german: 'in 2 Minuten', russian: 'через 2 минуты' },
    { german: 'um halb 6', russian: 'в половине 6' },
    { german: 'nie', russian: 'никогда' },
    { german: 'bald', russian: 'скоро' },
    { german: 'ab Montag', russian: 'с понедельника' },
    { german: 'gegen 5 Uhr', russian: 'около 5 часов' },
    { german: 'seit einem Jahr', russian: 'с года' },
    { german: 'morgens', russian: 'по утрам' },
    { german: 'mittags', russian: 'в обеденный час' },
    { german: 'nachmittags', russian: 'пополудни' },
    { german: 'abends', russian: 'по вечерам' },
    { german: 'immer', russian: 'всегда' },
    { german: 'nie', russian: 'никогда' },
    { german: 'oft', russian: 'часто' },
    { german: 'selten', russian: 'редко' },
    { german: 'morgen Früh (morgen früh)', russian: 'завтра утром' },
    { german: 'heute Abend', russian: 'сегодня вечером' },
    { german: 'am Montag', russian: 'в понедельник' },
    { german: 'am Dienstag', russian: 'во вторник' },
    { german: 'am Mittwoch', russian: 'в среду' },
    { german: 'am Donnerstag', russian: 'в четверг' },
    { german: 'am Freitag', russian: 'в пятницу' },
    { german: 'am Samstag', russian: 'в субботу' },
    { german: 'am Sonntag', russian: 'в воскресенье' },
    { german: 'am Morgen', russian: 'утром' },
    { german: 'am Abend', russian: 'вечером' },
    { german: 'in der Nacht', russian: 'ночью' },
    { german: 'am Tage', russian: 'днём' },
    { german: 'nach links', russian: 'налево' },
    { german: 'nach rechts', russian: 'направо' },
    { german: 'geradeaus', russian: 'прямо' },
    { german: 'vorwärts', russian: 'вперёд' },
    { german: 'rückwärts', russian: 'назад' },
    { german: 'im Januar', russian: 'в январе' },
    { german: 'im Februar', russian: 'в феврале' },
    { german: 'im März', russian: 'в марте' },
    { german: 'im April', russian: 'в апреле' },
    { german: 'im Mai', russian: 'в мае' },
    { german: 'im Juni', russian: 'в июне' },
    { german: 'im Juli', russian: 'в июле' },
    { german: 'im August', russian: 'в августе' },
    { german: 'im September', russian: 'в сентябре' },
    { german: 'im Oktober', russian: 'в октябре' },
    { german: 'im November', russian: 'в ноябре' },
    { german: 'im Dezember', russian: 'в декабре' },
    { german: 'Ich gieße Blumen', russian: 'я поливаю цветы' },
    { german: 'Ich arbeite im Garten', russian: 'я работаю в саду' },
    { german: 'Ich lese eine Zeitung', russian: 'я читаю газету' },
    { german: 'Ich gehe ins Bett', russian: 'я иду спать (в кровать)' },
    { german: 'Ich räume meine Wohnung auf', russian: 'я убираю свою квартиру' },
    { german: 'Ich fahre Fahrrad', russian: 'я еду на велосипеде' },
    { german: 'Ich gehe ins Konzert', russian: 'я иду на концерт' },
    { german: 'Ich schreibe einen Brief', russian: 'я пишу письмо' },
    { german: 'Ich gehe spazieren', russian: 'я иду гулять' },
    { german: 'Ich sehe fern', russian: 'я смотрю телевизор' }
];

//ПРИЛАГАТЕЛЬНЫЕ
const words5 = [
  { german: 'gelb', russian: 'жёлтый' },
    { german: 'violett', russian: 'фиолетовый' },
    { german: 'blau', russian: 'синий, голубой' },
    { german: 'orange', russian: 'оранжевый' },
    { german: 'grün', russian: 'зелёный' },
    { german: 'teuer', russian: 'дорого' },
    { german: 'billig', russian: 'дёшево' },
    { german: 'gesund', russian: 'здоровый' },
    { german: 'krank', russian: 'больной' },
    { german: 'gefährlich', russian: 'опасный' },
    { german: 'schwach', russian: 'слабый' },
    { german: 'stark', russian: 'сильный' },
    { german: 'überhaupt', russian: 'вообще' },
    { german: 'trotzdem', russian: 'несмотря на это' },
    { german: 'übrigens', russian: 'кстати' },
    { german: 'kurzum', russian: 'словом' },
    { german: 'daher', russian: 'оттуда' },
    { german: 'sicher', russian: 'уверенно' },
    { german: 'unbedingt', russian: 'непременно' },
    { german: 'zum Beispiel', russian: 'например' },
    { german: 'selbstverständlich', russian: 'разумеется' }
];

//ДОБАВЛЕННЫЕ НОВЫЕ СЛОВА
const words6 = [
  { german: 'ab, Ab morgen muss ich arbeiten', russian: 'Я должен работать с завтрашнего для' },
  { german: 'дописать слова', russian: 'дописать слова' },
];

// Объявляем переменную для отслеживания текущего массива слов
let currentWords = words1;

// Функция для обновления содержимого карточки по ID слова и перевода
function updateCardContent(frontWordId, backTranslationId, wordsArray) {
  const frontWordElement = document.getElementById(frontWordId);
  const backTranslationElement = document.getElementById(backTranslationId);

  // Здесь вы можете использовать вашу логику для выбора случайного слова и перевода из массива
  const randomIndex = Math.floor(Math.random() * wordsArray.length);
  const randomWord = wordsArray[randomIndex];

  // Обновляем содержимое карточки с новым словом и переводом
  frontWordElement.innerText = randomWord.german;
  backTranslationElement.innerText = randomWord.russian;
}

// Вызываем функцию updateCardContent() для каждой карточки чтобы показать первое слово и перевод при загрузке страницы
updateCardContent('frontWord1', 'backTranslation1', words1);
updateCardContent('frontWord2', 'backTranslation2', words2);
updateCardContent('frontWord3', 'backTranslation3', words3);
updateCardContent('frontWord4', 'backTranslation4', words4);
updateCardContent('frontWord5', 'backTranslation5', words5);
updateCardContent('frontWord6', 'backTranslation6', words6);

let isFlipping = false; // Добавляем переменную для отслеживания состояния переворота

// Функция переворота карточки
function flipCard(frontWordId, backTranslationId, wordsArray) {
  if (isFlipping) return; // Если карточка в процессе переворота, просто выходим

  const card = document.getElementById(frontWordId).closest('.card');
  card.classList.toggle('flipped');
  isFlipping = true;

  // Добавляем обработчик события окончания анимации переворота
  card.addEventListener('transitionend', function handleTransitionEnd() {
      // После окончания анимации переворота
      if (card.classList.contains('flipped')) {
          updateCardContent(frontWordId, backTranslationId, wordsArray); // Обновляем слово и перевод только после второго клика и переворота в положение "flipped"
      }
      isFlipping = false;
      card.removeEventListener('transitionend', handleTransitionEnd); // Удаляем обработчик события после использования
  });
}




