//A
const words1 = [
  { german: 'Ab morgen muss ich arbeiten.', russian: 'С завтрашнего дня мне нужно работать.' },
  { german: 'Ich bin oft im Büro, aber nur für wenige Stunden.', russian: 'Я часто в офисе, но всего на несколько часов.' },
  { german: 'Wir fahren um zwölf Uhr ab.', russian: 'Мы выезжаем в двенадцать часов.' },
  { german: 'Vor der Abfahrt rufe ich an.', russian: 'Перед отправлением я позвоню.' },
  { german: 'Ich muss meine Schlüssel abgeben.', russian: 'Мне нужно сдать свои ключи.' },
  { german: 'Wann kann ich den Schrank bei dir abholen?', russian: 'Когда я могу забрать шкаф у тебя?' },
  { german: 'Wir müssen noch meinen Bruder abholen.', russian: 'Мы должны еще забрать моего брата.' },
  { german: 'Da ist ein Brief für dich ohne Absender.', russian: 'Здесь есть письмо для тебя без отправителя.' },
  { german: 'Achtung! Das dürfen Sie nicht tun.', russian: 'Внимание! Вы не должны это делать.' },
  { german: 'Können Sie mir seine Adresse sagen?', russian: 'Вы можете сказать мне его адрес?' },
  { german: 'Alles Gute!', russian: 'Всего наилучшего!' },
  { german: 'Das ist alles.', russian: 'Это все.' },
  { german: 'Sind alle da?', russian: 'Все здесь?' },
  { german: 'Alle Freunde kommen.', russian: 'Все друзья приходят.' },
  { german: 'Hast du alles?', russian: 'У тебя есть все?' },
  { german: 'Er kommt allein.', russian: 'Он идет один.' },
  { german: 'Also, es ist so: ...', russian: 'Итак, дело в том, что ...' },
  { german: 'Er hat Zeit, also muss er uns helfen.', russian: 'У него есть время, так что он должен помочь нам.' },
  { german: 'Wie alt sind Sie?', russian: 'Сколько вам лет?' },
  { german: 'Sie sehen aber nicht so alt aus.', russian: 'Вы, однако, не выглядите так старо.' },
  { german: 'Mein Auto ist schon sehr alt.', russian: 'Моя машина уже очень старая.' },
  { german: 'Wir wohnen in einem sehr alten Haus.', russian: 'Мы живем в очень старом доме.' },
  { german: 'Köln ist eine alte Stadt.', russian: 'Кёльн - старый город.' },
  { german: 'Alter: 26 Jahre.', russian: 'Возраст: 26 лет.' },
  { german: 'Fahren Sie an der nächsten Straße nach rechts.', russian: 'Поверните направо на следующей улице.' },
  { german: 'Wir treffen uns am Bahnhof.', russian: 'Мы встречаемся на вокзале.' },
  { german: 'Am nächsten Montag geht es leider nicht.', russian: 'На следующий понедельник, к сожалению, не получится.' },
  { german: 'Was darf ich dir anbieten?', russian: 'Что я могу предложить тебе?' },
  { german: 'Heute sind Sportschuhe im Angebot.', russian: 'Сегодня спортивные ботинки по акции.' },
  { german: 'WiIlst du diese Jacke?', russian: 'Ты хочешь эту куртку?' },
  { german: '– Nein, ich möchte die andere.', russian: '– Нет, я хочу другую.' },
  { german: 'Hier fängt die Bahnhofstraße an.', russian: 'Здесь начинается улица Банхофштрассе.' },
  { german: 'Der Unterricht fängt gleich an.', russian: 'Урок начинается сразу.' },
  { german: 'Sie wohnt am Anfang der Straße.', russian: 'Она живет в начале улицы.' },
  { german: 'Wir machen Anfang Juli Urlaub.', russian: 'Мы отдыхаем в начале июля.' },
  { german: 'Da musst du dieses Wort anklicken.', russian: 'Здесь тебе нужно кликнуть на это слово.' },
  { german: 'Wann kommt dieser Zug in Hamburg an?', russian: 'Когда этот поезд прибывает в Гамбург?' },
  { german: 'Auf diesem Plan steht nur die Ankunft(-szeit) der Züge.', russian: 'На этом плане указано только время прибытия поездов.' },
  { german: 'Auf dem Formular müssen Sie an mehreren Stellen etwas ankreuzen.', russian: 'На форме вам нужно поставить отметку в нескольких местах.' },
  { german: 'Mach bitte das Licht an!', russian: 'Включи, пожалуйста, свет!' },
  { german: 'Wo kann ich mich anmelden?', russian: 'Где я могу зарегистрироваться?' },
  { german: 'Eine Anmeldung für diesen Kurs ist nicht mehr möglich.', russian: 'Регистрация на этот курс больше невозможна.' },
  { german: 'Schreiben Sie auch eine Anrede und einen Gruß.', russian: 'Не забудьте написать обращение и приветствие.' },
  { german: 'Kann man Sie anrufen?', russian: 'Можно вам позвонить?' },
  { german: 'Peter ruft kurz seine Freundin an.', russian: 'Петер кратко звонит своей подруге.' },
  { german: 'Sie bekommt viele Anrufe auf ihrem Handy.', russian: 'Она получает много звонков на свой мобильный.' },
  { german: 'Wir sind im Moment nicht da. Sprechen Sie bitte auf den Anrufbeantworter.', russian: 'Мы сейчас не находимся. Пожалуйста, оставьте сообщение на автоответчике.' },
  { german: 'Hören Sie die Ansagen.', russian: 'Слушайте анонсы.' },
  { german: 'In Mannheim haben Sie Anschluss nach Saarbrücken.', russian: 'В Мангейме у вас есть пересадка на Саарбрюккен.' },
  { german: 'Ist das die Anmeldung für einen Telefonanschluss?', russian: 'Это регистрация на телефонный номер?' },
  { german: 'Heute Nacht war das Licht an.', russian: 'Сегодня ночью свет горел.' },
  { german: 'Er antwortet nicht.', russian: 'Он не отвечает.' },
  { german: 'Er gibt leider keine Antwort.', russian: 'К сожалению, он не дает ответа.' },
  { german: 'Ich habe Ihre Anzeige in der Zeitung gelesen.', russian: 'Я видел ваше объявление в газете.' },
  { german: 'Ich muss mich noch anziehen.', russian: 'Мне еще нужно одеться.' },
  { german: 'Wir haben ein Apartment gemietet.', russian: 'Мы сняли апартаменты.' },
  { german: 'Ein Pfund Äpfel bitte.', russian: 'Пундт яблок, пожалуйста.' },
  { german: 'Guten Appetit!', russian: 'Приятного аппетита!' },
  { german: 'Wo arbeiten Sie?', russian: 'Где вы работаете?' },
  { german: 'Mein Bruder sucht Arbeit.', russian: 'Мой брат ищет работу.' },
  { german: 'Es gibt bei uns viele Leute, die schon lange arbeitslos sind.', russian: 'У нас много людей, которые долго безработные.' },
  { german: 'An meinem Arbeitsplatz fehlt ein Drucker.', russian: 'На моем рабочем месте не хватает принтера.' },
  { german: 'Mein Arm tut weh.', russian: 'У меня болит рука.' },
  { german: 'Morgen habe ich einen Termin bei meiner Ärztin.', russian: 'Завтра у меня встреча у моей докторши.' },
  { german: 'Ich bin auch Spanier.', russian: 'Я тоже испанец.' },
  { german: 'Die Kinder spielen auf der Straße.', russian: 'Дети играют на улице.' },
  { german: 'Auf Wiedersehen.', russian: 'До свидания.' },
  { german: 'Wie heißt das auf Deutsch?', russian: 'Как это называется по-немецки?' },
  { german: 'Das ist eine schwere Aufgabe.', russian: 'Это сложное задание.' },
  { german: 'Der Kurs hört in einer Woche auf.', russian: 'Курс заканчивается через неделю.' },
  { german: 'Hier hört die Bahnhofstraße auf.', russian: 'Здесь заканчивается улица Банхофштрассе.' },
  { german: 'Du brauchst den Schlüssel nicht. Die Wohnung ist auf.', russian: 'Тебе не нужен ключ. Квартира открыта.' },
  { german: 'Ich muss immer um vier Uhr aufstehen.', russian: 'Мне всегда нужно вставать в четыре часа.' },
  { german: 'Soll ich aufstehen?', russian: 'Мне вставать?' },
  { german: 'In diesem Haus gibt es keinen Aufzug.', russian: 'В этом доме нет лифта.' },
  { german: 'Er hat blaue Augen.', russian: 'У него голубые глаза.' },
  { german: 'Er kommt aus Brasilien.', russian: 'Он из Бразилии.' },
  { german: 'Morgen machen wir einen Ausflug nach Heidelberg.', russian: 'Завтра мы отправляемся на экскурсию в Гейдельберг.' },
  { german: 'Füllen Sie bitte dieses Formular aus.', russian: 'Пожалуйста, заполните эту форму.' },
  { german: 'Wo ist der Ausgang?', russian: 'Где выход?' },
  { german: 'Können Sie mir eine Auskunft geben?', russian: 'Вы можете дать мне информацию?' },
  { german: 'Fahren Sie ins Ausland?', russian: 'Вы едете за границу?' },
  { german: 'SInd Sie Ausländerin?', russian: 'Вы иностранка?' },
  { german: 'Leider habe ich nur ausländisches Geld.', russian: 'К сожалению, у меня есть только иностранная валюта.' },
  { german: 'Mach bitte das Licht aus!', russian: 'Пожалуйста, выключи свет!' },
  { german: 'Ist die Aussage richtig oder falsch?', russian: 'Высказывание верное или неверное?' },
  { german: 'Das sieht schön aus.', russian: 'Это выглядит красиво.' },
  { german: 'Das Licht ist aus.', russian: 'Свет выключен.' },
  { german: 'Die Schule ist aus.', russian: 'Школа закрыта.' },
  { german: 'Wo muss ich aussteigen?', russian: 'Где мне нужно выходить?' },
  { german: 'Hier ist mein Ausweis.', russian: 'Вот мой удостоверение.' },
  { german: 'Zieh die Schuhe aus, bitte!', russian: 'Сними обувь, пожалуйста!' },
  { german: 'Er kommt mit dem Auto.', russian: 'Он приезжает на машине.' },
  { german: 'Wo geht‘s hier bitte zur Autobahn?', russian: 'Как пройти к автобану, пожалуйста?' },
  { german: 'Die Fahrkarten gibt es nur am Automaten.', russian: 'Билеты есть только в автомате.' },
  { german: 'Du musst nichts machen. Das geht automatisch.', russian: 'Тебе ничего делать не нужно. Это происходит автоматически.' }
  ];
  
  //B
  const words2 = [
    { german: 'Mein Kind ist noch ein Baby.', russian: 'Моему ребенку всего лишь год.' },
  { german: 'Ich geh mal schnell zur Bäckerei.', russian: 'Я быстро пойду в булочную.' },
  { german: 'Wir haben kein großes Bad.', russian: 'У нас нет большой ванной.' },
  { german: 'Ich bade nicht so gern, ich dusche lieber.', russian: 'Мне не нравится принимать ванны, я предпочитаю душ.' },
  { german: 'Wir fahren lieber mit der Bahn.', russian: 'Мы предпочитаем ездить на поезде.' },
  { german: 'Ich nehme die nächste Bahn.', russian: 'Я возьму следующий поезд.' },
  { german: 'Komme ich hier zum Bahnhof?', russian: 'Подойдет ли это для поезда?' },
  { german: 'Auf welchem Bahnsteig fährt der Zug?', russian: 'С какого перрона отправляется поезд?' },
  { german: 'Ich komme bald.', russian: 'Я скоро приду.' },
  { german: 'Die Wohnung hat auch einen kleinen Balkon.', russian: 'У квартиры также есть небольшой балкон.' },
  { german: 'Drei Bananen, bitte!', russian: 'Три банана, пожалуйста!' },
  { german: 'Die Bank schließt schon um vier Uhr.', russian: 'Банк закрывается уже в четыре.' },
  { german: 'Er sitzt im Park auf einer Bank und liest.', russian: 'Он сидит в парке на скамейке и читает.' },
  { german: 'Muss ich bar zahlen oder geht‘s auch mit Karte?', russian: 'Нужно ли мне платить наличными или можно картой?' },
  { german: 'Seit gestern tut mir der Bauch weh.', russian: 'Со вчерашнего дня у меня болит живот.' },
  { german: 'Vorsicht, fahr nicht an den Baum!', russian: 'Осторожно, не врезайся в дерево!' },
  { german: 'Fragen Sie die Beamtin an Schalter acht!', russian: 'Спросите у служащей у окна номер восемь!' },
  { german: 'Was bedeutet das Wort?', russian: 'Что означает это слово?' },
  { german: 'Das Spiel beginnt um 15.30 Uhr.', russian: 'Игра начинается в 15:30.' },
  { german: 'Offenbach liegt bei Frankfurt.', russian: 'Оффенбах находится рядом с Франкфуртом.' },
  { german: 'Ich wohne bei meinen Eltern.', russian: 'Я живу у родителей.' },
  { german: 'Bei uns regnet es heute.', russian: 'У нас сегодня идет дождь.' },
  { german: 'Er arbeitet bei der Polizei.', russian: 'Он работает в полиции.' },
  { german: 'Beide Eltern arbeiten.', russian: 'Оба родителя работают.' },
  { german: 'Wir kommen beide.', russian: 'Мы оба придем.' },
  { german: 'Mein rechtes Bein tut weh.', russian: 'Моя правая нога болит.' },
  { german: 'Kannst du mir ein Beispiel sagen?', russian: 'Можешь мне привести пример?' },
  { german: 'Viele meiner Verwandten, z. B. meine beiden Brüder, arbeiten auch hier.', russian: 'Многие из моих родственников, например, мои два брата, тоже работают здесь.' },
  { german: 'Picasso ist sehr bekannt.', russian: 'Пикассо очень известен.' },
  { german: 'Ein Bekannter von mir heißt Klaus.', russian: 'Мой знакомый зовут Клаус.' },
  { german: 'Haben Sie meinen Brief bekommen?', russian: 'Вы получили мое письмо?' },
  { german: 'Was bekommen Sie?', russian: 'Что вы получаете?' },
  { german: 'Dieses Medikament bekommen Sie in der Apotheke.', russian: 'Этот препарат вы можете получить в аптеке.' },
  { german: 'Die Aufzüge bitte nicht benutzen!', russian: 'Пожалуйста, не пользуйтесь лифтами!' },
  { german: 'Was sind Sie von Beruf?', russian: 'Кем вы работаете?' },
  { german: 'Was ist Ihr Beruf?', russian: 'Какая у вас профессия?' },
  { german: 'Die Nummer ist immer besetzt.', russian: 'Линия всегда занята.' },
  { german: 'Der Platz ist besetzt.', russian: 'Место занято.' },
  { german: 'Ich möchte gern den Dom besichtigen.', russian: 'Я хотел бы осмотреть собор.' },
  { german: 'Es geht mir schon besser.', russian: 'Мне уже лучше.' },
  { german: 'Am besten treffen wir uns morgen.', russian: 'Самое лучшее, если мы встретимся завтра.' },
  { german: 'Wir möchten bestellen, bitte.', russian: 'Мы хотим заказать, пожалуйста.' },
  { german: 'Dieses Buch haben wir nicht – sollen wir es für Sie bestellen?', russian: 'У нас нет этой книги, должны ли мы заказать ее для вас?' },
  { german: 'Darf ich dich besuchen?', russian: 'Могу я навестить тебя?' },
  { german: 'Wir brauchen noch ein Kinderbett.', russian: 'Нам нужна еще детская кроватка.' },
  { german: 'Wo muss ich bezahlen?', russian: 'Где мне нужно платить?' },
  { german: 'Noch ein Bier bitte.', russian: 'Еще одно пиво, пожалуйста.' },
  { german: 'Hast du ein Bild von deinem Sohn?', russian: 'У тебя есть фотография твоего сына?' },
  { german: 'Die Jacke kostet nur 10 Euro! Die ist aber billig!', russian: 'Куртка стоит всего 10 евро! Она действительно дешевая!' },
  { german: 'Ein Kilo Birnen, bitte!', russian: 'Килограмм груш, пожалуйста!' },
  { german: 'Ich fahre nur bis Stuttgart.', russian: 'Я еду только до Штутгарта.' },
  { german: 'Ich warte bis morgen.', russian: 'Я жду до завтра.' },
  { german: 'Ich spreche Englisch, Französisch und ein bisschen Deutsch.', russian: 'Я говорю на английском, французском и немного на немецком.' },
  { german: 'Eine Tasse Kaffee, bitte!', russian: 'Чашка кофе, пожалуйста!' },
  { german: 'Sprechen Sie bitte leise!', russian: 'Пожалуйста, говорите тише!' },
  { german: 'Ich habe noch eine Bitte.', russian: 'У меня еще одна просьба.' },
  { german: 'Darf ich Sie um etwas bitten?', russian: 'Могу я попросить вас о чем-то?' },
  { german: 'Der Kaffee schmeckt bitter.', russian: 'Кофе горький на вкус.' },
  { german: 'Ich bleibe heute zu Hause.', russian: 'Сегодня я остаюсь дома.' },
  { german: 'Wir bleiben nur bis morgen.', russian: 'Мы остаемся только до завтра.' },
  { german: 'Hast du einen Bleistift?', russian: 'У тебя есть карандаш?' },
  { german: 'Von diesem Hotel hat man einen guten Blick auf den Rhein.', russian: 'Из этого отеля открывается хороший вид на Рейн.' },
  { german: 'Gefallen dir die Blumen?', russian: 'Тебе нравятся цветы?' },
  { german: 'Schreiben Sie Ihre Lösungen bitte auf den Antwortbogen.', russian: 'Пожалуйста, запишите свои решения на бланке ответов.' },
  { german: 'Sie ist böse auf mich.', russian: 'Она зла на меня.' },
  { german: 'Brauchst du die Zeitung noch?', russian: 'Тебе еще нужна газета?' },
  { german: 'Wie breit ist der Schrank?', russian: 'Какова ширина шкафа?' },
  { german: 'Haben Sie einen Brief für mich?', russian: 'У вас есть для меня письмо?' },
  { german: 'Kaufst du bitte Briefmarken bei der Post.', russian: 'Пожалуйста, купи марки на почте.' },
  { german: 'Bringen Sie mir bitte noch einen Kaffee!', russian: 'Пожалуйста, принесите мне еще кофе!' },
  { german: 'Wir müssen ihn zum Arzt bringen.', russian: 'Нам нужно его отвести к врачу.' },
  { german: 'Haben Sie auch Weißbrot?', russian: 'У вас есть белый хлеб?' },
  { german: 'Nimm noch ein paar Brote für die Fahrt mit.', russian: 'Возьми еще несколько булок для дороги.' },
  { german: 'Möchtest du Brötchen zum Frühstück?', russian: 'Ты хочешь булочки на завтрак?' },
  { german: 'Sein Bruder arbeitet auch hier.', russian: 'Его брат тоже работает здесь.' },
  { german: 'Gute Bücher sind oft sehr teuer.', russian: 'Хорошие книги часто очень дорогие.' },
  { german: 'In diesem Wörterbuch finden Sie mehr als 20.000 Wörter.', russian: 'В этом словаре вы найдете более 20 000 слов.' },
  { german: 'Diesen Buchstaben gibt es in meiner Sprache nicht.', russian: 'Такой буквы нет в моем языке.' },
  { german: 'Bitte buchstabieren Sie Ihren Namen.', russian: 'Пожалуйста, произнесите ваше имя по буквам.' },
  { german: 'Wann kommt der nächste Bus?', russian: 'Когда идет следующий автобус?' },
  { german: 'Für mich bitte ein Brötchen mit Butter und Käse.', russian: 'Для меня, пожалуйста, булочка с маслом и сыром.' }
  ];
  
  //C
  const words3 = [
    { german: 'Sollen wir uns im Café treffen?', russian: 'Давай встретимся в кафе?' },
  { german: 'Bring bitte deine Lieblings-CD mit.', russian: 'Пожалуйста, принеси свой любимый диск.' },
  { german: 'Wir haben eine neue Chefin.', russian: 'У нас новая начальница.' },
  { german: 'Von Mainz nach Frankfurt sind es circa fünfzig Kilometer.', russian: 'От Майнца до Франкфурта около пятидесяти километров.' },
  { german: 'Wann bekommst du deinen neuen Computer?', russian: 'Когда ты получишь свой новый компьютер?' }
  ];
  
  //D
  const words4 = [
    { german: 'Sollen wir uns im Café treffen?', russian: 'Давай встретимся в кафе?' },
  { german: 'Bring bitte deine Lieblings-CD mit.', russian: 'Пожалуйста, принеси свой любимый диск.' },
  { german: 'Wir haben eine neue Chefin.', russian: 'У нас новая начальница.' },
  { german: 'Von Mainz nach Frankfurt sind es circa fünfzig Kilometer.', russian: 'От Майнца до Франкфурта около пятидесяти километров.' },
  { german: 'Wann bekommst du deinen neuen Computer?', russian: 'Когда ты получишь свой новый компьютер?' },
  { german: 'Du kennst doch die Post. Daneben ist die Bank.', russian: 'Ты же знаешь почту. Рядом банк.' },
  { german: 'Ich danke Ihnen für die Einladung.', russian: 'Я благодарю вас за приглашение.' },
  { german: 'Vielen Dank!', russian: 'Большое спасибо!' },
  { german: 'Herzlichen Dank!', russian: 'Сердечное спасибо!' },
  { german: 'Soll ich Ihnen helfen? - Nein, danke!', russian: 'Могу я вам помочь? - Нет, спасибо!' },
  { german: 'Ich muss noch schnell zur Post, dann komme ich.', russian: 'Мне нужно еще быстро в почту, потом приду.' },
  { german: 'Bitte schreiben Sie noch das Datum auf das Formular.', russian: 'Пожалуйста, напишите еще дату в форму.' },
  { german: 'Wie lange dauert der Film?', russian: 'Сколько длится фильм?' },
  { german: 'Ist das dein Auto?', russian: 'Это твоя машина?' },
  { german: 'Ist das deins?', russian: 'Это твое?' },
  { german: 'Ich kann nicht kommen, denn ich bin krank.', russian: 'Я не могу прийти, так как болен.' },
  { german: 'Ich nehme das da.', russian: 'Я возьму это там.' },
  { german: 'Hier ist der Brief, den du suchst.', russian: 'Вот письмо, которое ты ищешь.' },
  { german: 'Die Fahrkarte bekommst du am Bahnhof.', russian: 'Билет ты получишь на вокзале.' },
  { german: 'Die Blumen sind für dich.', russian: 'Цветы для тебя.' },
  { german: 'Ich nehme lieber diesen Kuchen.', russian: 'Я лучше возьму этот торт.' },
  { german: 'Gefallen dir die Blumen?', russian: 'Тебе нравятся цветы?' },
  { german: 'Heute abend gehen wir in die Disco tanzen.', russian: 'Сегодня вечером мы идем в дискотеку танцевать.' },
  { german: 'Meine Tochter ist krank. Wir gehen zum Doktor.', russian: 'Моя дочь болеет. Мы идем к врачу.' },
  { german: 'Wollen Sie ein Doppelzimmer oder ein Einzelzimmer?', russian: 'Вы хотите двухместный номер или одноместный?' },
  { german: 'Meine Familie lebt in einem Dorf.', russian: 'Моя семья живет в деревне.' },
  { german: 'Deine Tasche kannst du dorthin stellen.', russian: 'Твою сумку ты можешь поставить туда.' },
  { german: 'Dort ist unser Haus.', russian: 'Там наш дом.' },
  { german: 'Wollen wir draußen sitzen?', russian: 'Посидим ли мы на улице?' },
  { german: 'Bitte drucke das Formular für mich.', russian: 'Пожалуйста, распечатай эту форму для меня.' },
  { german: 'Mein Drucker ist kaputt.', russian: 'Мой принтер сломался.' },
  { german: 'Drück hier, dann geht der Computer an.', russian: 'Нажми здесь, потом компьютер включится.' },
  { german: 'Am besten gehen Sie durch die Breite Straße.', russian: 'Лучше всего идите через улицу Брайт.' },
  { german: 'Ich habe die Durchsage nicht verstanden.', russian: 'Я не понял объявление.' },
  { german: 'Sie dürfen hier nicht rauchen.', russian: 'Здесь нельзя курить.' },
  { german: 'Darf ich Sie zu einem Kaffee einladen?', russian: 'Могу я пригласить вас на кофе?' },
  { german: 'Es darf nicht mehr als 15 Euro kosten.', russian: 'Это не должно стоить больше 15 евро.' },
  { german: 'Hast du etwas zu trinken? Ich habe großen Durst.', russian: 'У тебя есть что-нибудь попить? Я очень х thirsty.' },
  { german: 'Ich bade nicht so gern, ich dusche lieber.', russian: 'Мне не нравится принимать ванны, я предпочитаю душ.' },
  { german: 'Unsere Wohnung hat nur eine Dusche.', russian: 'У нас в квартире только душ.' }
  ];
  
  //E
  const words5 = [
    { german: 'An der nächsten Ecke links.', russian: 'На следующем углу налево.' },
    { german: 'Das ist mein (Ehe-) Mann/meine (Ehe-) Frau.', russian: 'Это мой (супруг) / моя (супруга).' },
    { german: 'Möchtest du ein Ei zum Frühstück?', russian: 'Хочешь яйцо на завтрак?' },
    { german: 'Hast du es eilig?', russian: 'У тебя спешка?' },
    { german: 'Ich nehme ein Bier. Willst du auch eins?', russian: 'Я возьму пиво. Ты тоже хочешь?' },
    { german: 'Ist hier einer, der das kann?', russian: 'Есть кто-то здесь, кто может это сделать?' },
    { german: 'Die Prüfung ist ganz einfach.', russian: 'Экзамен совсем простой.' },
    { german: 'Hin und zurück? – Nein, bitte nur einfach.', russian: 'Туда и обратно? - Нет, пожалуйста, только в одну сторону.' },
    { german: 'Ich brauche nur ein einfaches Zimmer.', russian: 'Мне нужен просто одноместный номер.' },
    { german: 'Der Eingang ist um die Ecke.', russian: 'Вход за углом.' },
    { german: 'Ich muss noch für morgen einkaufen.', russian: 'Мне еще нужно сходить за покупками на завтра.' },
    { german: 'Darf ich Sie zu einem Kaffee einladen?', russian: 'Могу ли я пригласить вас на кофе?' },
    { german: 'Danke für die Einladung!', russian: 'Спасибо за приглашение!' },
    { german: 'Diese Prüfung mache ich nicht noch einmal.', russian: 'Этот экзамен я не буду сдавать еще раз.' },
    { german: 'Schnell, steig ein, der Zug fährt gleich.', russian: 'Быстро, садись, поезд поедет сразу.' },
    { german: 'Der Preis für den Eintritt ist 5 Euro.', russian: 'Цена входа составляет 5 евро.' },
    { german: 'Haben Sie noch ein Einzelzimmer?', russian: 'У вас есть еще одноместный номер?' },
    { german: 'Meine Eltern leben in Spanien.', russian: 'Мои родители живут в Испании.' },
    { german: 'Ich habe Ihre E-Mail nicht bekommen.', russian: 'Я не получил ваше письмо.' },
    { german: 'Auf dem Brief steht dein Name, also bist du der Empfänger.', russian: 'На письме написано твое имя, значит, ты получатель.' },
    { german: 'Welchen Wein können Sie mir empfehlen?', russian: 'Какой вином вы можете мне порекомендовать?' },
    { german: 'Die Straße endet hier.', russian: 'Улица заканчивается здесь.' },
    { german: 'Sie wohnt am Ende der Straße.', russian: 'Она живет в конце улицы.' },
    { german: 'Er bekommt sein Geld am Ende des Monats.', russian: 'Он получает свои деньги в конце месяца.' },
    { german: 'Entschuldigen Sie bitte!', russian: 'Извините, пожалуйста!' },
    { german: 'Entschuldigung! – Bitte.', russian: 'Прошу прощения! - Пожалуйста.' },
    { german: 'Er heißt Ali.', russian: 'Его зовут Али.' },
    { german: 'Das Ergebnis des Tests bekommen Sie in zwei Wochen.', russian: 'Результат теста вы получите через две недели.' },
    { german: 'Kannst du mir das erklären?', russian: 'Можешь мне это объяснить?' },
    { german: 'Rauchen ist hier nicht erlaubt.', russian: 'Здесь курить запрещено.' },
    { german: 'Dieser Film ist nur für Erwachsene.', russian: 'Этот фильм только для взрослых.' },
    { german: 'Wir müssen euch etwas erzählen!', russian: 'Мы должны вам что-то рассказать!' },
    { german: 'Es regnet.', russian: 'Идет дождь.' },
    { german: 'Was gibt es zu essen?', russian: 'Что есть поесть?' },
    { german: 'Das Essen ist heute sehr gut.', russian: 'Еда сегодня очень хорошая.' },
    { german: 'Euer Kurs beginnt heute.', russian: 'Ваш курс начинается сегодня.' }
      
  ];
  
  //F
  const words6 = [
    { german: 'Ich fahre mit dem Auto zur Arbeit.', russian: 'Я еду на работу на машине.' },
    { german: 'Bitte nicht mit dem Fahrer sprechen!', russian: 'Пожалуйста, не разговаривайте с водителем!' },
    { german: 'Hast du schon eine Fahrkarte?', russian: 'У тебя уже есть билет?' },
    { german: 'Fährst du mit dem Fahrrad oder mit dem Auto?', russian: 'Ты едешь на велосипеде или на машине?' },
    { german: 'Das ist falsch.', russian: 'Это неправильно.' },
    { german: 'Meine Familie lebt in Spanien.', russian: 'Моя семья живет в Испании.' },
    { german: 'Meine Familiennamen sind García González.', russian: 'Мои фамилии - Гарсия Гонсалес.' },
    { german: 'Bei „Familienstand“ musst du „ledig“ ankreuzen.', russian: 'В разделе "Семейное положение" ты должен отметить "не женат/не замужем".' },
    { german: 'Die Farbe gefällt mir gut.', russian: 'Мне нравится цвет.' },
    { german: 'Schicken Sie uns einfach ein Fax!', russian: 'Просто отправьте нам факс!' },
    { german: 'z. B. Feierabend, Feiertag', russian: 'например, конец рабочего дня, праздничный день' },
    { german: 'Am Montag ist Feiertag.', russian: 'В понедельник праздник.' },
    { german: 'Wir feiern heute meinen Geburtstag.', russian: 'Сегодня мы отмечаем мой день рождения.' },
    { german: 'Herr Müller ist nicht da, er fehlt schon seit drei Tagen.', russian: 'Господин Мюллер отсутствует, его нет уже три дня.' },
    { german: 'Was fehlt Ihnen?', russian: 'Что вам не хватает?' },
    { german: 'Diesen Fehler mache ich immer.', russian: 'Эту ошибку я всегда делаю.' },
    { german: 'Wollen wir heute Abend mal fernsehen?', russian: 'Давай сегодня вечером посмотрим телевизор?' },
    { german: 'Bist du fertig?', russian: 'Ты готов?' },
    { german: 'Ist mein Auto schon fertig?', russian: 'Моя машина уже готова?' },
    { german: 'Haben Sie Feuer?', russian: 'У вас есть огонь?' },
    { german: 'Mein Mann hat noch immer Fieber.', russian: 'У моего мужа все еще жар.' },
    { german: 'Ich möchte gern diesen Film sehen.', russian: 'Я бы хотел посмотреть этот фильм.' },
    { german: 'Wir müssen den Schlüssel finden.', russian: 'Мы должны найти ключ.' },
    { german: 'Er arbeitet jetzt bei einer anderen Firma.', russian: 'Теперь он работает в другой фирме.' },
    { german: 'Ich esse gern Fisch. Fleisch mag ich nicht.', russian: 'Я люблю есть рыбу. Мясо мне не нравится.' },
    { german: 'Eine Flasche Bier, bitte.', russian: 'Пиво, пожалуйста.' },
    { german: 'Fleisch mag ich nicht.', russian: 'Мясо мне не нравится.' },
    { german: 'Ich fliege nicht gern. Deshalb fahre ich mit dem Zug.', russian: 'Я не люблю летать. Поэтому еду на поезде.' },
    { german: 'Wann fliegst du ab?', russian: 'Когда ты летишь?' },
    { german: 'Der Abflug ist um 11.20 Uhr.', russian: 'Вылет в 11:20.' },
    { german: 'Kannst du mich zum Flughafen bringen?', russian: 'Ты можешь меня отвезти в аэропорт?' },
    { german: 'Das Flugzeug aus Berlin kommt heute später an.', russian: 'Самолет из Берлина прилетает сегодня позже.' },
    { german: 'Sie müssen dieses Formular ausfüllen.', russian: 'Вы должны заполнить эту форму.' },
    { german: 'Darf ich ein Foto machen?', russian: 'Можно сделать фотографию?' },
    { german: 'Er möchte Sie etwas fragen. Wann kommen Sie?', russian: 'Он хочет вас о чем-то спросить. Когда вы приходите?' },
    { german: 'Ich habe eine Frage.', russian: 'У меня есть вопрос.' },
    { german: 'Das ist Frau Becker.', russian: 'Это госпожа Беккер.' },
    { german: 'Guten Tag, Frau Schmitt!', russian: 'Добрый день, госпожа Шмитт!' },
    { german: 'Hier arbeiten mehr Frauen als Männer.', russian: 'Здесь работает больше женщин, чем мужчин.' },
    { german: 'Ist der Platz noch frei?', russian: 'Это место еще свободно?' },
    { german: 'In meiner Freizeit spiele ich oft Fußball.', russian: 'В свободное время я часто играю в футбол.' },
    { german: 'Das weiß ich nicht; ich bin fremd hier.', russian: 'Я не знаю; я здесь чужой.' },
    { german: 'Ich freue mich auf den Urlaub.', russian: 'Я жду с нетерпением отпуска.' },
    { german: 'Das ist ein Freund von mir.', russian: 'Это мой друг.' },
    { german: 'Das ist meine Freundin.', russian: 'Это моя подруга.' },
    { german: 'Früher waren wir oft zusammen im Kino.', russian: 'Раньше мы часто ходили в кино вместе.' },
    { german: 'Am Sonntag frühstücke ich gern im Bett.', russian: 'В воскресенье я люблю завтракать в постели.' },
    { german: 'Möchtest du ein Ei zum Frühstück?', russian: 'Хочешь яйцо на завтрак?' },
    { german: 'Die Führung durch das Haus beginnt in 3 Minuten.', russian: 'Экскурсия по дому начнется через 3 минуты.' },
    { german: 'Das ist für Sie.', russian: 'Это для вас.' },
    { german: 'Das ist der Schlüssel für die Haustür.', russian: 'Это ключ от входной двери.' },
    { german: 'Das ist das Brot für morgen.', russian: 'Это хлеб на завтра.' },
    { german: 'Der linke Fuß tut mir weh.', russian: 'Левая нога болит.' },
    { german: 'Spielt ihr gerne Fußball?', russian: 'Вы любите играть в футбол?' }
    
  ];

  //G
  const words7 = [
    { german: 'Wir haben leider keinen Garten.', russian: 'К сожалению, у нас нет сада.' },
    { german: 'Am Wochenende haben wir mehrere Gäste.', russian: 'На выходных у нас несколько гостей.' },
    { german: 'Kannst du mir bitte deinen Kugelschreiber geben?', russian: 'Можешь дать мне, пожалуйста, свою ручку?' },
    { german: 'Es gibt keine Karten mehr.', russian: 'Билетов больше нет.' },
    { german: 'Ich bin in Zagreb geboren.', russian: 'Я родился в Загребе.' },
    { german: 'Das Geburtsjahr Ihres Sohnes, bitte?', russian: 'Год рождения вашего сына, пожалуйста?' },
    { german: 'Bitte schreiben Sie Ihren Geburtsort auf das Formular.', russian: 'Пожалуйста, укажите свое место рождения в форме.' },
    { german: 'Herzlichen Glückwunsch zum Geburtstag!', russian: 'С днем рождения!' },
    { german: 'Das gefällt mir.', russian: 'Мне это нравится.' },
    { german: 'Fahr nicht gegen den Baum!', russian: 'Не врезайся в дерево!' },
    { german: 'Ich bin gegen diese Lösung.', russian: 'Я против этого решения.' },
    { german: 'Wer spielt gegen wen?', russian: 'Кто играет против кого?' },
    { german: 'Ich weiß nicht, wie das geht.', russian: 'Я не знаю, как это делать.' },
    { german: 'Wie geht‘s?', russian: 'Как дела?' },
    { german: 'Jetzt muss ich (aber) leider gehen.', russian: 'Теперь, к сожалению, мне нужно уходить.' },
    { german: 'Ich muss zum Arzt gehen.', russian: 'Мне нужно пойти к врачу.' },
    { german: 'Das geht nicht!', russian: 'Это невозможно!' },
    { german: 'Wem gehört das?', russian: 'Кому это принадлежит?' },
    { german: 'Hast du noch Geld?', russian: 'У тебя еще есть деньги?' },
    { german: 'Gemüse brauchen wir auch noch.', russian: 'Нам также нужны овощи.' },
    { german: 'Wollen Sie Ihr Gepäck mitnehmen?', russian: 'Хотите взять свой багаж?' },
    { german: 'Da kommt er ja gerade.', russian: 'Вот он и идет.' },
    { german: 'Gehen Sie immer geradeaus!', russian: 'Идите всегда прямо!' },
    { german: 'Ich gehe gerne einkaufen.', russian: 'Я люблю ходить по магазинам.' },
    { german: 'Die Geschäfte schließen um 18.30 Uhr.', russian: 'Магазины закрываются в 18:30.' },
    { german: 'Danke für das schöne Geschenk.', russian: 'Спасибо за прекрасный подарок.' },
    { german: 'Ich habe leider keine Geschwister.', russian: 'К сожалению, у меня нет братьев и сестер.' },
    { german: 'Das Gespräch mit Frau Kunz ist um 14 Uhr.', russian: 'Разговор с госпожой Кунц назначен на 14:00.' },
    { german: 'Gestern war ich krank.', russian: 'Вчера я был болен.' },
    { german: 'Meine Frau ist gestern gestorben.', russian: 'Моя жена умерла вчера.' },
    { german: 'Mein Lieblingsgetränk ist Tomatensaft.', russian: 'Мой любимый напиток - томатный сок.' },
    { german: 'Bei „Gewicht“ schreibst du: 62 Kilo.', russian: 'В разделе "Вес" пишешь: 62 килограмма.' },
    { german: 'Wer gewinnt das Spiel?', russian: 'Кто выиграет эту игру?' },
    { german: 'Bitte noch ein Glas Wein!', russian: 'Пожалуйста, еще один бокал вина!' },
    { german: 'Wir brauchen noch drei Gläser.', russian: 'Нам еще нужны три бокала.' },
    { german: 'Sie können mir glauben, es ist so.', russian: 'Вы можете мне поверить, это так.' },
    { german: 'Ich glaube, er kommt gleich.', russian: 'Думаю, он скоро придет.' },
    { german: 'Das ist mir gleich.', russian: 'Мне все равно.' },
    { german: 'Das ist der gleiche Preis.', russian: 'Это одинаковая цена.' },
    { german: 'Ich komme gleich.', russian: 'Я скоро приду.' },
    { german: 'Der ICE nach Berlin hält heute an Gleis 12.', russian: 'Экспресс до Берлина останавливается сегодня на платформе 12.' },
    { german: 'Viel Glück!', russian: 'Удачи!' },
    { german: 'Meine Kinder sind glücklich verheiratet.', russian: 'Мои дети счастливо женаты/замужем.' },
    { german: 'Herzlichen Glückwunsch zum Geburtstag.', russian: 'С днем рождения!' },
    { german: 'Heute haben wir dreißig Grad.', russian: 'Сегодня тридцать градусов.' },
    { german: 'Ich gratuliere dir!', russian: 'Поздравляю тебя!' },
    { german: 'Heute grillen wir im Garten.', russian: 'Сегодня мы будем жарить мясо на гриле в саду.' },
    { german: 'Mein Bruder und ich sind gleich groß.', russian: 'Мой брат и я одинакового роста.' },
    { german: 'Frankfurt ist eine große Stadt.', russian: 'Франкфурт - большой город.' },
    { german: 'Haben Sie das auch in Größe 40?', russian: 'У вас это есть размера 40?' },
    { german: 'Meine Großeltern leben in Japan.', russian: 'Мои дедушка и бабушка живут в Японии.' },
    { german: 'Meine Großmutter heißt Eva.', russian: 'Моя бабушка зовут Ева.' },
    { german: 'Mein Großvater ist schon 80.', russian: 'Моему дедушке уже 80.' },
    { german: 'Die erste Gruppe beginnt um 16 Uhr.', russian: 'Первая группа начинается в 16:00.' },
    { german: 'Viele Grüße an Ihre Frau.', russian: 'Многие приветы вашей жене.' },
    { german: 'Mit freundlichen Grüßen', russian: 'С наилучшими пожеланиями' },
    { german: 'Der Pass ist nicht mehr gültig.', russian: 'Паспорт больше не действителен.' },
    { german: 'Dort gibt es günstige Angebote.', russian: 'Там есть выгодные предложения.' },
    { german: 'Das finde ich gut.', russian: 'Я нахожу это хорошим.' },
    { german: 'Ich komme um 13 Uhr. – Gut!', russian: 'Я приду в 13:00. - Хорошо!' },
    { german: 'Guten Morgen!', russian: 'Доброе утро!' },
    { german: 'Ein gutes neues Jahr!', russian: 'С Новым годом!' },
    { german: 'Guten Appetit!', russian: 'Приятного аппетита!' }
  ];

  //H
  const words8 = [
    { german: 'Sie hat lange Haare.', russian: 'У нее длинные волосы.' },
    { german: 'Ich habe ein neues Auto.', russian: 'У меня есть новая машина.' },
    { german: 'Ein Hähnchen mit Pommes bitte!', russian: 'Курочка с картофельными палочками, пожалуйста!' },
    { german: 'Möchten Sie Vollpension oder Halbpension?', russian: 'Вы хотите полный пансион или полупансион?' },
    { german: 'Wir treffen uns in Halle B', russian: 'Мы встречаемся в зале B.' },
    { german: 'Hallo Inge! Wie geht’s?', russian: 'Привет, Инге! Как дела?' },
    { german: 'Dieser Zug hält nicht in Rüdesheim.', russian: 'Этот поезд не останавливается в Рюдесхайме.' },
    { german: 'An der nächsten Haltestelle müssen Sie aussteigen.', russian: 'На следующей остановке вам нужно выйти.' },
    { german: 'Er gibt mir die Hand.', russian: 'Он подает мне руку.' },
    { german: 'In der Schule bitte die Handys ausmachen!', russian: 'В школе, пожалуйста, выключите мобильные телефоны!' },
    { german: 'In welchem Haus wohnst du?', russian: 'В каком доме ты живешь?' },
    { german: 'Ich gehe jetzt nach Hause.', russian: 'Я иду домой.' },
    { german: 'Paul ist nicht zu Hause.', russian: 'Пауль сейчас не дома.' },
    { german: 'Kannst du mir bei den Hausaufgaben helfen?', russian: 'Ты можешь мне помочь с домашними заданиями?' },
    { german: 'Die Hausfrau/der Hausmann wäscht, kocht und kauft ein.', russian: 'Домохозяйка/домохозяин стирает, готовит и делает покупки.' },
    { german: 'Ich komme aus der Schweiz. Das ist meine Heimat.', russian: 'Я из Швейцарии. Это моя родина.' },
    { german: 'Meine Schwester heiratet einen Japaner.', russian: 'Моя сестра выходит замуж за японца.' },
    { german: 'Ich heiße Charlotte Meier.', russian: 'Меня зовут Шарлотта Майер.' },
    { german: 'Wie heißt das auf Deutsch?', russian: 'Как это называется по-немецки?' },
    { german: 'Können Sie mir helfen, bitte?', russian: 'Вы можете мне помочь, пожалуйста?' },
    { german: 'Im Sommer ist es bis 21 Uhr hell.', russian: 'Летом светло до 21 часа.' },
    { german: 'In der neuen Küche fehlt noch der Herd.', russian: 'В новой кухне еще нет плиты.' },
    { german: 'Guten Tag, Herr Sommer!', russian: 'Добрый день, мистер Зоммер!' },
    { german: 'Herzlichen Glückwunsch!', russian: 'Сердечные поздравления!' },
    { german: 'Heute ist ein schöner Tag.', russian: 'Сегодня прекрасный день.' },
    { german: 'Hier ist 06131-553221, Pamela Linke.', russian: 'Вот номер 06131-553221, Памела Линке.' },
    { german: 'Hier wohne ich.', russian: 'Здесь я живу.' },
    { german: 'Hilfe! Bitte helfen Sie mir!', russian: 'Помощь! Пожалуйста, помогите мне!' },
    { german: 'Brauchen Sie meine Hilfe?', russian: 'Вам нужна моя помощь?' },
    { german: 'Die Tür zum Aussteigen ist hinten.', russian: 'Дверь для выхода находится сзади.' },
    { german: 'Meine Hobbys sind Wandern und Schwimmen.', russian: 'Мои хобби - походы и плавание.' },
    { german: 'Der Mount Everest ist 8.880 Meter hoch.', russian: 'Эверест имеет высоту 8880 метров.' },
    { german: 'Zur dieser Hochzeit kommen mehr als fünfzig Gäste.', russian: 'На эту свадьбу придет более пятидесяти гостей.' },
    { german: 'Ich hole zwei Flaschen Wasser aus der Küche.', russian: 'Я возьму две бутылки воды из кухни.' },
    { german: 'Hör mal! Was ist das?', russian: 'Послушай! Что это?' },
    { german: 'Ich habe das Lied schon mal gehört.', russian: 'Я уже слышал эту песню.' },
    { german: 'Im Urlaub sind wir in einem Hotel am Meer.', russian: 'В отпуске мы будем в отеле у моря.' },
    { german: 'Der Hund ist noch jung.', russian: 'Собака еще молодая.' },
    { german: 'Ich habe Hunger! Wann ist das Essen fertig?', russian: 'Я голоден! Когда будет готова еда?' }

  ];

  //I
  const words9 = [
    { german: 'Ich heiße Veronika.', russian: 'Меня зовут Вероника.' },
    { german: 'Gib ihr/ihm bitte das Buch.', russian: 'Дай ей/ему, пожалуйста, книгу.' },
    { german: 'Ruf ihn bitte an.', russian: 'Пожалуйста, позвони ему.' },
    { german: 'Frau Bast kommt immer zu spät.', russian: 'Госпожа Баст всегда опаздывает.' },
    { german: 'Ich wohne in Wiesbaden.', russian: 'Я живу в Висбадене.' },
    { german: 'Der Zug kommt in fünf Minuten.', russian: 'Поезд прибудет через пять минут.' },
    { german: 'Frau Rausch arbeitet in einem Geschäft.', russian: 'Госпожа Рауш работает в магазине.' },
    { german: 'Komm, wir gehen ins Kino.', russian: 'Иди, мы пойдем в кино.' },
    { german: 'Wenn Sie Fragen haben, gehen Sie zur Information.', russian: 'Если у вас есть вопросы, обратитесь в информацию.' },
    { german: 'Wir haben hier wichtige Informationen für Sie.', russian: 'У нас есть важная информация для вас.' },
    { german: 'Unser Deutschkurs ist international: Silvana kommt aus Italien, Conchi aus Spanien, Yin aus China ...', russian: 'Наш курс немецкого языка международный: Сильвана из Италии, Кончи из Испании, Йин из Китая ...' },
    { german: 'Das findest du im Internet.', russian: 'Ты найдешь это в интернете.' },

  ];

  //J
  const words10 = [
    { german: 'Sind Sie Herr Watanabe? – Ja.', russian: 'Вы господин Ватанабе? - Да.' },
    { german: 'Zieh dir eine Jacke an. Es ist kalt.', russian: 'Наденьте куртку, холодно.' },
    { german: 'Blumen kannst du in jedem Bahnhof kaufen.', russian: 'Цветы можно купить в любом вокзале.' },
    { german: 'Jetzt machen wir eine Pause.', russian: 'Теперь мы делаем перерыв.' },
    { german: 'Jenny hat einen neuen Job bei der Post.', russian: 'У Дженни новая работа на почте.' },
    { german: 'Viele Jugendliche kaufen gern ein.', russian: 'Многие подростки любят делать покупки.' },
    { german: 'Claudia ist 21. – Was? Noch so jung?', russian: 'Клаудия 21 год. - Что? Еще так молодая?' },
    { german: 'Ich habe zwei Kinder. Einen Jungen und ein Mädchen.', russian: 'У меня двое детей. Мальчик и девочка.' }
  ];

  //K
  const words11 = [
    { german: 'Zum Frühstück trinke ich immer Kaffee.', russian: 'На завтрак я всегда пью кофе.' },
    { german: 'Das Glas war teuer. Es geht sehr leicht kaputt.', russian: 'Это стекло было дорогое. Оно очень легко ломается.' },
    { german: 'Ich schreibe meinen Bekannten eine Karte aus dem Urlaub.', russian: 'Я пишу моим знакомым открытку из отпуска.' },
    { german: 'Wollen wir Karten spielen?', russian: 'Давай сыграем в карты?' },
    { german: 'Ich möchte auch etwas essen. Bringen Sie mir die Karte, bitte.', russian: 'Я тоже хочу что-то поесть. Принесите мне меню, пожалуйста.' },
    { german: 'Kann ich auch mit Karte (be-) zahlen?', russian: 'Можно платить картой?' },
    { german: 'Für Pommes frites braucht man Kartoffeln.', russian: 'Для картофель фри нужны картофель.' },
    { german: 'Zahlen Sie bitte an der Kasse.', russian: 'Пожалуйста, оплатите у кассы.' },
    { german: 'Tim kauft sich ein neues Auto.', russian: 'Тим покупает себе новую машину.' },
    { german: 'Es gibt keine Eintrittskarten mehr.', russian: 'Билетов больше нет.' },
    { german: 'Kennen Sie diese Frau? – Nein, leider nicht.', russian: 'Вы знакомы с этой женщиной? - Нет, к сожалению.' },
    { german: 'Wir sind neu hier. Wir möchten Sie kennenlernen.', russian: 'Мы новые здесь. Мы хотим познакомиться с вами.' },
    { german: 'Wie viele Kinder haben Sie?', russian: 'Сколько у вас детей?' },
    { german: 'Die kleine Laura geht schon in den Kindergarten.', russian: 'Маленькая Лаура уже ходит в детский сад.' },
    { german: 'Wir sehen heute Abend im Kino einen schönen Film.', russian: 'Сегодня вечером мы смотрим в кино хороший фильм.' },
    { german: 'Am Kiosk bekommen Sie Getränke, Zigaretten und Zeitungen.', russian: 'На киоске вы можете купить напитки, сигареты и газеты.' },
    { german: 'Kommst du mit? – Klar!', russian: 'Идешь с нами? - Конечно!' },
    { german: 'In unserer Klasse sind fünfundzwanzig Schüler.', russian: 'В нашем классе двадцать пять учеников.' },
    { german: 'Im Zug fahre ich immer 2. Klasse.', russian: 'В поезде я всегда еду вторым классом.' },
    { german: 'Wo finde ich Kleidung? – Jacken im ersten, Jeans im zweiten Stock.', russian: 'Где я могу найти одежду? - Куртки на первом, джинсы на втором этаже.' },
    { german: 'Eltville ist eine kleine Stadt am Rhein.', russian: 'Эльтвиль - небольшой город на Рейне.' },
    { german: 'Herr Georgi kann gut kochen.', russian: 'Господин Георги хорошо готовит.' },
    { german: 'Ist das Ihr Koffer?', russian: 'Это ваш чемодан?' },
    { german: 'Wie heißt die neue Kollegin?', russian: 'Как зовут новую коллегу?' },
    { german: 'Woher kommen Sie? – Aus Frankreich.', russian: 'Откуда вы? - Из Франции.' },
    { german: 'Kommst du mit ins Schwimmbad?', russian: 'Идешь со мной в бассейн?' },
    { german: 'Ich kann Deutsch und Russisch.', russian: 'Я говорю по-немецки и по-русски.' },
    { german: 'Können Sie mir helfen?', russian: 'Вы можете мне помочь?' },
    { german: 'Das Geld überweisen wir am ersten März auf Ihr Konto.', russian: 'Мы переведем деньги на ваш счет первого марта.' },
    { german: 'Mein Kopf tut weh!', russian: 'У меня болит голова!' },
    { german: 'Wie viel kostet das? – 10 Euro.', russian: 'Сколько это стоит? - 10 евро.' },
    { german: 'Ich kann heute nicht zur Arbeit kommen, ich bin krank und liege im Bett.', russian: 'Сегодня я не могу прийти на работу, я болен и лежу в кровати.' },
    { german: 'Ich kriege 15 Euro in der Stunde für meine Arbeit.', russian: 'Я получаю 15 евро в час за свою работу.' },
    { german: 'Der neue Herd kommt in die Küche.', russian: 'Новая плита придет на кухню.' },
    { german: 'Ich nehme ein Stück Kuchen.', russian: 'Я возьму кусок торта.' },
    { german: 'Hast du einen Kugelschreiber für mich?', russian: 'У тебя есть ручка для меня?' },
    { german: 'Haben wir noch Milch? – Ja, im Kühlschrank.', russian: 'У нас еще есть молоко? - Да, в холодильнике.' },
    { german: 'Ich bin kulturell interessiert. Ich gehe oft ins Museum.', russian: 'Я интересуюсь культурой. Я часто хожу в музеи.' },
    { german: 'Jede Mutter kümmert sich um ihre kleinen Kinder.', russian: 'Каждая мать заботится о своих маленьких детях.' },
    { german: 'Einen Moment, bitte. Ich habe eine Kundin.', russian: 'Минуту, пожалуйста. У меня клиентка.' },
    { german: 'Der Deutschkurs geht bis zum Sommer.', russian: 'Курс немецкого идет до лета.' },
    { german: 'Ricardo hat kurzes Haar.', russian: 'У Рикардо короткие волосы.' }
  ];

  //l
  const words12 = [
    { german: 'Die Kinder lachen viel.', russian: 'Дети много смеются.' },
    { german: 'Im Buchladen können Sie Bücher kaufen.', russian: 'В книжном магазине вы можете купить книги.' },
    { german: 'Italien ist ein schönes Land.', russian: 'Италия - прекрасная страна.' },
    { german: 'Die Jeans ist zu lang.', russian: 'Джинсы слишком длинные.' },
    { german: 'Wie lange fährt der Zug von Hamburg nach Berlin?', russian: 'Сколько времени идет поезд из Гамбурга в Берлин?' },
    { german: 'Könnten Sie bitte etwas langsamer sprechen?', russian: 'Не могли бы вы говорить немного медленнее?' },
    { german: 'Ich möchte nicht Auto fahren, ich möchte laufen.', russian: 'Я не хочу ехать на машине, я хочу идти.' },
    { german: 'Nicht so laut! Das Baby schläft.', russian: 'Не так громко! Ребенок спит.' },
    { german: 'Sie lebt bei ihrer Schwester.', russian: 'Она живет у своей сестры.' },
    { german: 'Ihre Eltern leben nicht mehr.', russian: 'Ее родители больше не живут.' },
    { german: 'Das Leben in diesem Land ist teuer.', russian: 'Жизнь в этой стране дорогая.' },
    { german: 'Lebensmittel bekommen Sie im Supermarkt.', russian: 'Продукты питания вы можете купить в супермаркете.' },
    { german: 'Sind Sie verheiratet? – Nein. Ledig.', russian: 'Вы женаты? - Нет. Холост.' },
    { german: 'Legen Sie das Buch auf den Tisch.', russian: 'Положите книгу на стол.' },
    { german: 'Unsere Deutschlehrerin heißt Frau Müller.', russian: 'Наша учительница немецкого - Фрау Мюллер.' },
    { german: 'Der Koffer ist leicht.', russian: 'Чемодан легкий.' },
    { german: 'Deutsch ist nicht leicht.', russian: 'Немецкий не легкий.' },
    { german: 'Leider kann ich nicht kommen. Ich muss zum Arzt.', russian: 'К сожалению, я не могу прийти. Мне нужно к врачу.' },
    { german: 'Seid leise. Die anderen schlafen schon.', russian: 'Будьте тихими. Остальные уже спят.' },
    { german: 'Wie lange lernen Sie schon Deutsch?', russian: 'Как долго вы изучаете немецкий?' },
    { german: 'Ich lese ein Buch von García Márquez.', russian: 'Я читаю книгу Гарсии Маркеса.' },
    { german: 'Morgen ist der letzte Kurstag.', russian: 'Завтра последний день курса.' },
    { german: 'In der Disko sind viele Leute.', russian: 'В дискотеке много людей.' },
    { german: 'Wo macht man hier das Licht an?', russian: 'Где здесь включают свет?' },
    { german: 'Liebe Susanne, lieber Hans,', russian: 'Дорогая Сюзанна, дорогой Ханс,' },
    { german: 'Ich liebe dich!', russian: 'Я тебя люблю!' },
    { german: 'Sie fährt lieber mit der Bahn.', russian: 'Она предпочитает ездить на поезде.' },
    { german: 'Mein Lieblingsfilm ist „Schwarze Augen“.', russian: 'Мой любимый фильм - "Черные глаза".' },
    { german: 'Welches ist dein Lieblingslied?', russian: 'Какая у тебя любимая песня?' },
    { german: 'Um neun Uhr liegt Judith noch im Bett.', russian: 'В девять часов Юдит все еще лежит в постели.' },
    { german: 'Frankfurt liegt am Main.', russian: 'Франкфурт находится на Майне.' },
    { german: 'Gehen Sie die nächste Straße links.', russian: 'Идите по следующей улице налево.' },
    { german: 'Dieser Lastkraftwagen ist sehr groß.', russian: 'Этот грузовик очень большой.' },
    { german: 'In unserer Straße gibt es ein neues Lokal.', russian: 'На нашей улице есть новое заведение.' },
    { german: 'Die Lösung ist ganz einfach.', russian: 'Решение совсем простое.' },
    { german: 'Frau Mertens ist lustig. Sie lacht immer.', russian: 'Фрау Мертенс забавная. Она всегда смеется.' }
  ];
  
  //M
  const words13 = [
    { german: 'Was machst du heute Abend?', russian: 'Что ты будешь делать сегодня вечером?' },
    { german: 'Ich muss jetzt das Essen machen.', russian: 'Мне сейчас нужно готовить еду.' },
    { german: 'Das macht 5 Euro 95.', russian: 'Это стоит 5 евро 95 центов.' },
    { german: 'Das macht nichts.', russian: 'Это ничего.' },
    { german: 'Familie Kurz bekommt ein Baby. – Junge oder Mädchen?', russian: 'Семья Курц ожидает ребенка. – Мальчик или девочка?' },
    { german: 'Hier darf man nicht rauchen.', russian: 'Здесь нельзя курить.' },
    { german: 'Mein Mann arbeitet bei der Polizei.', russian: 'Мой муж работает в полиции.' },
    { german: 'Kreuzen Sie bitte an: „weiblich“ oder „männlich“.', russian: 'Пожалуйста, отметьте: "женский" или "мужской".' },
    { german: 'Die Waschmaschine ist günstig.', russian: 'Стиральная машина недорогая.' },
    { german: 'Wir machen Urlaub am Meer.', russian: 'Мы отдыхаем на море.' },
    { german: 'Dieses Auto kostet 1.000 Euro mehr als das andere.', russian: 'Эта машина стоит на 1000 евро больше, чем та.' },
    { german: 'Mein Vater ist Arzt.', russian: 'Мой отец врач.' },
    { german: 'Die meisten Norddeutschen sind sehr groß.', russian: 'Большинство северных немцев очень высокие.' },
    { german: 'Die Menschen sind hier anders als bei uns.', russian: 'Люди здесь другие, чем у нас.' },
    { german: 'Ich möchte ein Auto mieten.', russian: 'Я хотел бы арендовать автомобиль.' },
    { german: 'Die Miete für diese Wohnung ist 600 Euro.', russian: 'Аренда за эту квартиру составляет 600 евро.' },
    { german: 'Die Milch steht im Kühlschrank.', russian: 'Молоко стоит в холодильнике.' },
    { german: 'Trinken Sie den Kaffee mit Milch?', russian: 'Вы пьете кофе с молоком?' },
    { german: 'Ich gehe einkaufen. Soll ich dir was mitbringen?', russian: 'Я иду за покупками. Нужно что-то привезти?' },
    { german: 'Ich gehe ins Kino. Kommst du mit?', russian: 'Я иду в кино. Пойдешь со мной?' },
    { german: 'Warum macht ihr nicht mit?', russian: 'Почему вы не присоединяетесь?' },
    { german: 'Nehmen wir meine Schwester ins Kino mit?', russian: 'Давайте возьмем мою сестру с собой в кино?' },
    { german: 'Der Lehrer steht in der Mitte des Klassenzimmers.', russian: 'Учитель стоит посередине класса.' },
    { german: 'Sind die Möbel neu?', russian: 'Мебель новая?' },
    { german: 'Was möchten Sie trinken?', russian: 'Что бы вы хотели выпить?' },
    { german: 'Magst du Kaffee oder Tee?', russian: 'Ты любишь кофе или чай?' },
    { german: 'Mit dieser Fahrkarte ist die Fahrt ab 9 Uhr möglich.', russian: 'С этим билетом поездка возможна с 9 часов.' },
    { german: 'Moment mal bitte!', russian: 'Минутку, пожалуйста!' },
    { german: 'Einen Moment bitte.', russian: 'Минутку, пожалуйста.' },
    { german: 'Morgen beginnt die Schule um 10 Uhr.', russian: 'Завтра школа начинается в 10 часов.' },
    { german: 'Ich bin müde. Ich gehe schlafen.', russian: 'Я устал. Пойду спать.' },
    { german: 'Öffnen Sie den Mund.', russian: 'Откройте рот.' },
    { german: 'Ich muss jeden Tag von 8 Uhr bis 18 Uhr arbeiten.', russian: 'Мне приходится работать каждый день с 8 до 18 часов.' },
    { german: 'Frau Berghäuser ist die Mutter von Michaela.', russian: 'Фрау Бергхойзер - мать Михаэлы.' }
  ];

  //N
  const words14 = [
    { german: 'Ich gehe jetzt nach Hause.', russian: 'Я иду домой сейчас.' },
    { german: 'Ich fliege nach München.', russian: 'Я лечу в Мюнхен.' },
    { german: 'Es ist schon 5 nach 12.', russian: 'Уже 5 минут после 12.' },
    { german: 'Sehen wir uns nächste Woche?', russian: 'Увидимся ли мы на следующей неделе?' },
    { german: 'Mein Name ist Thomas Schmidt.', russian: 'Меня зовут Томас Шмидт.' },
    { german: 'Mein Vorname ist Thomas; Schmidt ist der Familienname.', russian: 'Мое имя - Томас; Шмидт - фамилия.' },
    { german: 'Heute gibt es Hähnchen. Das nehme ich.', russian: 'Сегодня есть курица. Я возьму ее.' },
    { german: 'Ich nehme den Bus.', russian: 'Я иду на автобус.' },
    { german: 'Fährst du auch nach München? – Nein, ich habe keine Zeit.', russian: 'Ты тоже едешь в Мюнхен? – Нет, у меня нет времени.' },
    { german: 'Ich bin der neue Kollege.', russian: 'Я новый коллега.' },
    { german: 'Wir haben eine neue Wohnung.', russian: 'У нас новая квартира.' },
    { german: 'Das stimmt nicht.', russian: 'Это не верно.' },
    { german: 'Das ist doch schön, nicht?', russian: 'Это же хорошо, не так ли?' },
    { german: 'Das macht nichts.', russian: 'Ничего страшного.' },
    { german: 'Hier kaufe ich nichts. Der Laden gefällt mir nicht.', russian: 'Здесь я ничего не покупаю. Мне не нравится магазин.' },
    { german: 'Er kommt nie pünktlich.', russian: 'Он никогда не приходит вовремя.' },
    { german: 'Vielleicht kommt er noch.', russian: 'Может быть, он еще придет.' },
    { german: 'Wir warten noch fünf Minuten.', russian: 'Мы подождем еще пять минут.' },
    { german: 'Ich habe noch 20 Euro.', russian: 'У меня еще есть 20 евро.' },
    { german: '75 kg. Sein Gewicht ist normal.', russian: '75 кг. Его вес нормальный.' },
    { german: 'Sie haben Zimmer Nummer zwölf.', russian: 'У вас номер комнаты двенадцать.' },
    { german: 'Welche Hausnummer haben Sie?', russian: 'Какой у вас номер дома?' },
    { german: 'Können Sie mir Ihre Nummer geben?', russian: 'Можете дать мне ваш номер?' },
    { german: 'Ich möchte nur ein Glas Wasser.', russian: 'Я бы хотел только стакан воды.' }
  ];

  //O
  const words15 = [
    { german: 'Ich wohne oben.', russian: 'Я живу наверху.' },
    { german: 'Im Sommer ist das Obst billig.', russian: 'Летом фрукты дешевые.' },
    { german: 'Wann können Sie kommen – heute oder morgen?', russian: 'Когда вы можете прийти - сегодня или завтра?' },
    { german: 'Ich öffne die Tür.', russian: 'Я открываю дверь.' },
    { german: 'Der Laden ist samstags bis 16.00 Uhr geöffnet.', russian: 'Магазин открыт по субботам до 16:00.' },
    { german: 'Petra treffe ich oft.', russian: 'Я часто встречаю Петру.' },
    { german: 'Ohne Geld kann er nichts kaufen.', russian: 'Без денег он ничего не может купить.' },
    { german: 'Den Salat machen wir ohne Öl.', russian: 'Салат мы делаем без масла.' },
    { german: 'Meine Oma ist schon tot.', russian: 'Моя бабушка уже умерла.' },
    { german: 'Mein Opa heißt Hans.', russian: 'Моего дедушку зовут Ханс.' },
    { german: 'Das ist in Ordnung.', russian: 'Это в порядке.' },
    { german: 'Der Ort liegt am Meer.', russian: 'Место находится у моря.' }
  ];

  //P
  const words16 = [
    { german: 'Hier sind Papier und Bleistift.', russian: 'Вот бумага и карандаш.' },
    { german: 'Haben Sie Ihre Papiere dabei?', russian: 'У вас есть документы с собой?' },
    { german: 'Sie ist meine Partnerin.', russian: 'Она моя партнерша.' },
    { german: 'Heute Abend machen wir eine Party.', russian: 'Сегодня вечером мы устраиваем вечеринку.' },
    { german: 'Im Hotel brauchst du deinen Pass.', russian: 'В отеле тебе понадобится твой паспорт.' },
    { german: 'Von 12.00 bis 12.30 Uhr haben wir Mittagspause.', russian: 'С 12:00 до 12:30 у нас обеденный перерыв.' },
    { german: 'Ich kaufe mir einen Stadtplan.', russian: 'Я куплю себе карту города.' },
    { german: 'Tut mir leid, der Platz ist besetzt.', russian: 'Извините, место занято.' },
    { german: 'Bitte nehmen Sie Platz!', russian: 'Прошу зайти, садиться!' },
    { german: 'Ich wohne Messeplatz 5.', russian: 'Я живу на Messeplatz 5.' },
    { german: 'Wo ist die Post, bitte?', russian: 'Где находится почта, пожалуйста?' },
    { german: 'Ist Post da?', russian: 'Есть ли почта?' },
    { german: 'Wie ist Ihre Postleitzahl?', russian: 'Какой у вас почтовый индекс?' },
    { german: 'Ich mache ein Praktikum bei Siemens.', russian: 'Я прохожу практику в Siemens.' },
    { german: 'Die Praxis ist ab acht Uhr geöffnet.', russian: 'Практика открыта с восьми часов.' },
    { german: 'Die Preise sind hoch.', russian: 'Цены высокие.' },
    { german: 'Mein Problem ist die Sprache.', russian: 'Моя проблема - язык.' },
    { german: 'Bitte schicken Sie mir einen Prospekt von Ihrem Hotel.', russian: 'Пожалуйста, пришлите мне брошюру вашего отеля.' },
    { german: 'Die Prüfung ist am Montag um 8.00 Uhr.', russian: 'Экзамен в понедельник в 8:00.' },
    { german: 'Der Bus fährt pünktlich um acht Uhr.', russian: 'Автобус отправляется точно в восемь часов.' },
    { german: 'Herr Müller ist immer pünktlich.', russian: 'Господин Мюллер всегда приходит вовремя.' }
  ];

  //R
  const words17 = [
    { german: 'Das Kind kann schon Rad fahren.', russian: 'Ребенок уже умеет кататься на велосипеде.' },
    { german: 'Ich rauche nicht.', russian: 'Я не курю.' },
    { german: 'Der Unterricht ist in Raum 332.', russian: 'Урок в аудитории 332.' },
    { german: 'Die Rechnung, bitte.', russian: 'Счет, пожалуйста.' },
    { german: 'Die Schillerstraße ist hier rechts.', russian: 'Улица Шиллера здесь направо.' },
    { german: 'Heute regnet es.', russian: 'Сегодня идет дождь.' },
    { german: 'Bei diesem Regen gehe ich nicht raus.', russian: 'При такой погоде я не выхожу на улицу.' },
    { german: 'Ich esse gern Reis.', russian: 'Я люблю есть рис.' },
    { german: 'Ich reise gern.', russian: 'Я люблю путешествовать.' },
    { german: 'Wir machen eine Reise nach Österreich.', russian: 'Мы отправляемся в путешествие в Австрию.' },
    { german: 'Mein Mann arbeitet im Reisebüro.', russian: 'Мой муж работает в туристическом агентстве.' },
    { german: 'Ich kaufe mir einen Reiseführer von Berlin.', russian: 'Я покупаю путеводитель по Берлину.' },
    { german: 'Unser Reiseführer heißt Peter.', russian: 'Наш гид зовут Петер.' },
    { german: 'Er hat das Fahrrad repariert.', russian: 'Он починил велосипед.' },
    { german: 'Die Reparatur ist sehr teuer.', russian: 'Ремонт очень дорогой.' },
    { german: 'Wir essen heute in einem Restaurant.', russian: 'Сегодня мы едим в ресторане.' },
    { german: 'Fragen Sie bitte im Hotel an der Rezeption.', russian: 'Пожалуйста, спросите в отеле на рецепции.' },
    { german: 'Habe ich das richtig verstanden?', russian: 'Понял ли я правильно?' },
    { german: 'Das ist richtig.', russian: 'Это верно.' },
    { german: 'Dieser Wein riecht gut.', russian: 'Это вино пахнет хорошо.' },
    { german: 'Ich möchte ein ruhiges Zimmer.', russian: 'Я бы хотел спокойный номер.' }
  ];

  //S
  const words18 = [
    { german: 'Möchtest du einen Apfelsaft?', russian: 'Хочешь яблочный сок?' },
    { german: 'Sag mal, wie geht es dir denn?', russian: 'Скажи, как ты?' },
    { german: 'Wie schmeckt dir der Salat?', russian: 'Как тебе салат?' },
    { german: 'Herr Ober, kann ich bitte Salz haben?', russian: 'Официант, можно мне соль, пожалуйста?' },
    { german: 'Dieser Satz ist sehr einfach.', russian: 'Это предложение очень простое.' },
    { german: 'Ich nehme lieber die S-Bahn.', russian: 'Я лучше возьму поезд S-Bahn.' },
    { german: 'Gehen Sie bitte zum Schalter drei!', russian: 'Пожалуйста, идите к окну номер три!' },
    { german: 'Die Sonne scheint.', russian: 'Солнце светит.' },
    { german: 'Bitte schicken Sie mir eine E-Mail.', russian: 'Пожалуйста, отправьте мне электронное письмо.' },
    { german: 'Haben Sie nicht das Schild gesehen?', russian: 'Вы не видели знак?' },
    { german: 'Ich möchte gern ein Schinkenbrot.', russian: 'Я бы хотел бутерброд с ветчиной.' },
    { german: 'Ich schlafe meistens acht Stunden.', russian: 'Я обычно сплю восемь часов.' },
    { german: 'Mir ist schlecht!', russian: 'Мне плохо!' },
    { german: 'Sie sehen schlecht aus.', russian: 'Вы выглядите плохо.' },
    { german: 'Wir haben schlechtes Wetter.', russian: 'У нас плохая погода.' },
    { german: 'Bitte, schließen Sie die Tür.', russian: 'Пожалуйста, закройте дверь.' },
    { german: 'Die Bank hat am Samstag geschlossen.', russian: 'Банк закрыт в субботу.' },
    { german: 'Ich muss jetzt Schluss machen.', russian: 'Мне теперь нужно завершить.' },
    { german: 'Zum Schluss gibt er uns allen die Hand.', russian: 'В конце он пожимает всем нам руки.' },
    { german: 'Ich gebe Ihnen noch den Zimmerschlüssel.', russian: 'Я дам вам еще ключ от комнаты.' },
    { german: 'Schmeckt das gut?', russian: 'Это вкусно?' },
    { german: 'Er fährt schnell.', russian: 'Он едет быстро.' },
    { german: 'Ist das Essen schon fertig?', russian: 'Еда уже готова?' },
    { german: 'Schönen Urlaub!', russian: 'Приятного отдыха!' },
    { german: 'Das ist sehr schön.', russian: 'Это очень красиво.' },
    { german: 'Die Gläser stehen im Schrank.', russian: 'Бокалы стоят в шкафу.' },
    { german: 'Er schreibt jeden Tag fünfzig E-Mails.', russian: 'Он пишет пятьдесят электронных писем каждый день.' },
    { german: 'Zieh die Schuhe aus!', russian: 'Сними туфли!' },
    { german: 'Meine Tochter geht schon in die Schule.', russian: 'Моя дочь уже ходит в школу.' },
    { german: 'Die Schule ist gleich hier um die Ecke.', russian: 'Школа прямо здесь за углом.' },
    { german: 'In meinem Kurs sind acht Schülerinnen und fünf Schüler.', russian: 'В моем курсе восемь девочек и пять мальчиков.' },
    { german: 'Ist Ihr Gepäck sehr schwer?', russian: 'Ваш багаж очень тяжелый?' },
    { german: 'Das ist eine schwere Arbeit.', russian: 'Это тяжелая работа.' },
    { german: 'Meine Schwester kommt am Dienstag.', russian: 'Моя сестра приезжает во вторник.' },
    { german: 'Ich schwimme jeden Tag einen Kilometer.', russian: 'Я плаваю каждый день километр.' },
    { german: 'Kommst du mit ins Schwimmbad?', russian: 'Идешь ли ты со мной в бассейн?' },
    { german: 'Komm, wir fahren zum Starnberger See.', russian: 'Иди, мы поедем к озеру Штарнбергерзее.' },
    { german: 'Ich kann dich nicht sehen.', russian: 'Я не вижу тебя.' },
    { german: 'Ich habe diesen Jungen schon einmal gesehen.', russian: 'Я уже видел этого мальчика однажды.' },
    { german: 'Danke sehr!', russian: 'Большое спасибо!' },
    { german: 'Das ist sehr schwer.', russian: 'Это очень тяжело.' },
    { german: 'Herr Müller ist in seinem Zimmer.', russian: 'Господин Мюллер в своей комнате.' },
    { german: 'Mir ist kalt.', russian: 'Мне холодно.' },
    { german: 'Ich bin dreiundzwanzig.', russian: 'Мне двадцать три года.' },
    { german: 'Das Licht ist noch an.', russian: 'Свет еще включен.' },
    { german: 'Das Fenster ist noch auf.', russian: 'Окно еще открыто.' },
    { german: 'Herr Meier ist schon weg.', russian: 'Господин Майер уже ушел.' },
    { german: 'Die Tür ist zu.', russian: 'Дверь закрыта.' },
    { german: 'Ich wohne seit drei Jahren in Köln.', russian: 'Я живу в Кёльне уже три года.' },
    { german: 'Er ist selbstständig.', russian: 'Он самостоятельный.' },
    { german: 'Sie müssen sich erst anmelden.', russian: 'Сначала вам нужно зарегистрироваться.' },
    { german: 'Wie heißt sie?', russian: 'Как её зовут?' },
    { german: 'Wie heißen Sie, bitte?', russian: 'Как вас зовут, пожалуйста?' },
    { german: 'Wo sitzen Sie?', russian: 'Где вы сидите?' },
    { german: 'Sie müssen das so machen!', russian: 'Вам нужно сделать это так!' },
    { german: 'Fahren Sie bitte nicht so schnell!', russian: 'Пожалуйста, не ездите так быстро!' },
    { german: 'Meine Frau ist so groß wie ich.', russian: 'Моя жена такая же высокая, как и я.' },
    { german: 'So, das war‘s/wär‘s!', russian: 'Вот, это было/было бы!' },
    { german: 'Das Sofa ist neu.', russian: 'Диван новый.' },
    { german: 'Bitte antworten Sie sofort.', russian: 'Пожалуйста, ответьте сразу.' },
    { german: 'Das ist Hans, mein Sohn.', russian: 'Это Ганс, мой сын.' },
    { german: 'Soll ich kommen?', russian: 'Я должен прийти?' },
    { german: 'Was soll ich mitbringen?', russian: 'Что мне принести?' },
    { german: 'Die Sonne scheint.', russian: 'Солнце светит.' },
    { german: 'Es ist schon spät, ich muss gehen.', russian: 'Уже поздно, мне пора идти.' },
    { german: 'Das können wir später machen.', russian: 'Мы можем это сделать позже.' },
    { german: 'Bringen Sie mir die Speisekarte, bitte.', russian: 'Принесите мне меню, пожалуйста.' },
    { german: 'Die Kinder spielen draußen.', russian: 'Дети играют на улице.' },
    { german: 'Spielen Sie Karten?', russian: 'Вы играете в карты?' },
    { german: 'Ich mache viel Sport.', russian: 'Я много занимаюсь спортом.' },
    { german: 'Welche Sprachen sprichst du?', russian: 'На каких языках ты говоришь?' },
    { german: 'Kann ich (mit) Herrn Klein sprechen?', russian: 'Могу я поговорить (с) господином Кляйн?' },
    { german: 'Heidelberg ist eine alte Stadt.', russian: 'Гейдельберг - старый город.' },
    { german: 'Ich glaube es nicht, aber es steht in der Zeitung.', russian: 'Я этому не верю, но это написано в газете.' },
    { german: 'Der Bus steht schon an der Haltestelle.', russian: 'Автобус уже стоит на остановке.' },
    { german: 'Ich habe eine neue Stelle.', russian: 'У меня новая работа.' },
    { german: 'Stell die Tasche rechts in die Ecke!', russian: 'Положи сумку справа в угол!' },
    { german: 'Unsere Wohnung liegt im ersten Stock.', russian: 'Наша квартира находится на первом этаже.' },
    { german: 'In welcher Straße wohnen Sie?', russian: 'На какой улице вы живете?' },
    { german: 'Wo fährt die Straßenbahn ab?', russian: 'Откуда отходит трамвай?' },
    { german: 'Ich studiere in Mainz.', russian: 'Я учусь в Майнце.' },
    { german: 'Das Studium beginnt im Oktober.', russian: 'Учеба начинается в октябре.' },
    { german: 'Ich bin Studentin.', russian: 'Я студентка.' },
    { german: 'Ich bin in einer Stunde zurück.', russian: 'Я вернусь через час.' },
    { german: 'Suchst du etwas?', russian: 'Ты что-то ищешь?' }
  ];

  //T
  const words19 = [
    { german: 'Tanzen Sie gern?', russian: 'Вы любите танцевать?' },
    { german: 'Ich habe die Schlüssel in der Tasche.', russian: 'У меня ключи в сумке.' },
    { german: 'Es gibt heute keinen Bus mehr.', russian: 'Сегодня больше нет автобусов.' },
    { german: 'Er fährt mit dem Taxi.', russian: 'Он поедет на такси.' },
    { german: 'Ich trinke morgens immer Tee.', russian: 'Я всегда пью чай по утрам.' },
    { german: 'Lies bitte auch den zweiten Teil.', russian: 'Пожалуйста, прочти также вторую часть.' },
    { german: 'Darf ich mal telefonieren?', russian: 'Можно мне позвонить?' },
    { german: 'Haben Sie Telefon?', russian: 'У вас есть телефон?' },
    { german: 'Am besten machen wir sofort einen Termin.', russian: 'Лучше мы назначим встречу сейчас же.' },
    { german: 'Der Test war einfach.', russian: 'Тест был легким.' },
    { german: 'Das ist mir zu teuer.', russian: 'Мне это слишком дорого.' },
    { german: 'Lesen Sie bitte diesen Text.', russian: 'Пожалуйста, прочтите этот текст.' },
    { german: 'Wir sprechen heute über das Thema „Essen und Trinken“.', russian: 'Сегодня мы будем говорить на тему "Еда и питье".' },
    { german: 'Wie viel kostet das Ticket?', russian: 'Сколько стоит билет?' },
    { german: 'Die Fotos liegen auf dem Tisch.', russian: 'Фотографии лежат на столе.' },
    { german: 'Das ist meine Tochter Katharina.', russian: 'Это моя дочь Катарина.' },
    { german: 'Wo ist die Toilette, bitte?', russian: 'Где туалет, пожалуйста?' },
    { german: 'Die Tomate ist noch grün.', russian: 'Помидор еще зеленый.' },
    { german: 'Sein Vater ist schon lange tot.', russian: 'Его отец умер уже давно.' },
    { german: 'Ich treffe in der Stadt einen Kollegen.', russian: 'Я встречаю в городе коллегу.' },
    { german: 'Wir treffen uns immer freitags.', russian: 'Мы встречаемся каждую пятницу.' },
    { german: 'Die Toilette? Die Treppe hoch und dann links.', russian: 'Туалет? Поднимитесь по лестнице и затем налево.' },
    { german: 'Möchtest du etwas trinken?', russian: 'Хочешь выпить что-нибудь?' },
    { german: 'Junge Leute sagen meistens „tschüss!“ und nicht „auf Wiedersehen“.', russian: 'Молодые люди чаще говорят "пока!" а не "до свидания".' },
    { german: 'Ich habe noch etwas zu tun.', russian: 'У меня еще есть что-то делать.' },
    { german: 'Was tut Ihr Mann?', russian: 'Чем занимается ваш муж?' }
  ];

  const words20 = [
    { german: 'Gehen Sie hier über die Straße.', russian: 'Перейдите дорогу здесь.' },
    { german: 'Er wohnt im zweiten Stock über Familie Meier.', russian: 'Он живет на втором этаже над семьей Майер.' },
    { german: 'Sind Sie über 18?', russian: 'Вам больше 18?' },
    { german: 'Du kannst bei mir übernachten.', russian: 'Ты можешь переночевать у меня.' },
    { german: 'Sie können das Geld auch überweisen.', russian: 'Вы также можете перевести деньги.' },
    { german: 'Es ist vier Uhr.', russian: 'Сейчас четыре часа.' },
    { german: 'Er kommt um sieben Uhr.', russian: 'Он приходит в семь часов.' },
    { german: 'Da kommt er gerade um die Ecke.', russian: 'Вот идет он прямо за углом.' },
    { german: 'Nächsten Monat ziehen wir um.', russian: 'Следующим месяцем мы переезжаем.' },
    { german: 'Peter und Helmut sind meine Söhne.', russian: 'Петер и Хельмут - мои сыновья.' },
    { german: 'Das ist unsere Lehrerin.', russian: 'Это наша учительница.' },
    { german: 'Er wohnt ganz unten im Haus.', russian: 'Он живет в самом низу дома.' },
    { german: 'Unter uns wohnt eine Familie mit drei Kindern.', russian: 'Под нами живет семья с тремя детьми.' },
    { german: 'Wir haben Unterricht von 8.00 bis 12.00 Uhr.', russian: 'У нас занятия с 8.00 до 12.00 часов.' },
    { german: 'Wo muss ich unterschreiben?', russian: 'Где мне нужно поставить подпись?' },
    { german: 'Hier fehlt noch Ihre Unterschrift.', russian: 'Здесь еще нет вашей подписи.' },
    { german: 'Ich nehme im September Urlaub.', russian: 'Я беру отпуск в сентябре.' }
  ];

  //V
  const words21 = [
    { german: 'Mein Vater ist Arbeiter.', russian: 'Мой отец рабочий.' },
    { german: 'Hier ist Rauchen verboten.', russian: 'Здесь курить запрещено.' },
    { german: 'Ich verdiene 1.500 Euro im Monat.', russian: 'Я зарабатываю 1500 евро в месяц.' },
    { german: 'Es gibt einen neuen Sportverein in der Stadt.', russian: 'В городе есть новый спортивный клуб.' },
    { german: 'Ich bin verheiratet und habe drei Kinder.', russian: 'Я женат и у меня трое детей.' },
    { german: 'Er verkauft sein altes Auto.', russian: 'Он продает свою старую машину.' },
    { german: 'Meine Mutter ist Verkäuferin im Kaufhaus.', russian: 'Моя мама продавец в универмаге.' },
    { german: 'Die Wohnung ist schon vermietet.', russian: 'Квартира уже сдана в аренду.' },
    { german: 'Unser Vermieter heißt Huber. Er wohnt auch hier.', russian: 'Наш арендодатель зовут Хубер. Он тоже здесь живет.' },
    { german: 'Können Sie mich verstehen?', russian: 'Вы меня понимаете?' },
    { german: 'Peter besucht seine Verwandten in Polen.', russian: 'Петер посещает своих родственников в Польше.' },
    { german: 'Hier regnet es viel.', russian: 'Здесь много дождей.' },
    { german: 'Ich komme vielleicht mit dem Bus.', russian: 'Я, возможно, приду на автобусе.' },
    { german: 'Das Auto von Felix ist kaputt.', russian: 'Автомобиль Феликса сломан.' },
    { german: 'Er kommt gerade von Köln/von zu Hause.', russian: 'Он только что приехал из Кёльна/из дома.' },
    { german: 'Der Termin war vor einer Stunde.', russian: 'Встреча была час назад.' },
    { german: 'Das Auto steht vor der Tür.', russian: 'Автомобиль стоит перед дверью.' },
    { german: 'Ich heiße Müller, mein Vorname ist Eva.', russian: 'Меня зовут Мюллер, мое имя - Ева.' },
    { german: 'Vorsicht! Da kommt ein Auto.', russian: 'Осторожно! Идет машина.' },
    { german: 'Wir wollen uns kennenlernen. Können Sie sich bitte vorstellen?', russian: 'Мы хотим познакомиться. Вы можете представиться?' },
    { german: 'Wie ist die Vorwahl von München?', russian: 'Какой код города Мюнхена?' }
  ];

  //W
  const words22 = [
    { german: 'Wir wandern um den Chiemsee.', russian: 'Мы гуляем вокруг озера Химзее.' },
    { german: 'Wann bist du fertig?', russian: 'Когда ты закончишь?' },
    { german: 'Wann kann ich Sie anrufen?', russian: 'Когда я могу вам позвонить?' },
    { german: 'Wann sind Sie geboren?', russian: 'Когда вы родились?' },
    { german: 'Können Sie ein paar Minuten warten?', russian: 'Вы можете подождать несколько минут?' },
    { german: 'Auf wen warten Sie?', russian: 'На кого вы ждете?' },
    { german: 'Warum kommt er nicht?', russian: 'Почему он не приходит?' },
    { german: 'Was ist das?', russian: 'Что это?' },
    { german: 'Was möchten Sie?', russian: 'Что бы вы хотели?' },
    { german: 'Was für eine Farbe möchten Sie?', russian: 'Какой цвет вы хотите?' },
    { german: 'Wo kann ich mir die Hände waschen?', russian: 'Где я могу помыть руки?' },
    { german: 'Ich muss morgen waschen.', russian: 'Я должен стирать завтра.' },
    { german: 'Ein Glas Wasser, bitte.', russian: 'Стакан воды, пожалуйста.' },
    { german: 'Ich muss zum Arzt. Mein Bein tut weh.', russian: 'Мне нужно к врачу. У меня болит нога.' },
    { german: 'Kreuzen Sie bitte an: „weiblich“ oder „männlich“.', russian: 'Пожалуйста, отметьте "женский" или "мужской".' },
    { german: 'Nein danke, ich möchte keinen Wein.', russian: 'Нет, спасибо, я не хочу вино.' },
    { german: 'Zum Bahnhof ist es nicht weit.', russian: 'До вокзала недалеко.' },
    { german: 'Der Bus fährt nicht weiter.', russian: 'Автобус больше не идет.' },
    { german: 'Welches Buch möchtest du?', russian: 'Какую книгу ты хочешь?' },
    { german: 'Es gibt viele Probleme auf der Welt.', russian: 'Есть много проблем в мире.' },
    { german: 'Ich habe leider nur wenig verstanden.', russian: 'К сожалению, я понял только немного.' },
    { german: 'Er verdient wenig.', russian: 'Он зарабатывает мало.' },
    { german: 'Wer ist das?', russian: 'Кто это?' },
    { german: 'Mein Sohn will Arzt werden.', russian: 'Мой сын хочет стать врачом.' },
    { german: 'Wir hatten schlechtes Wetter.', russian: 'У нас была плохая погода.' },
    { german: 'Dieses Formular ist sehr wichtig.', russian: 'Эта форма очень важна.' },
    { german: 'Wie heißt du?', russian: 'Как тебя зовут?' },
    { german: 'Er schreibt wie ein Kind.', russian: 'Он пишет как ребенок.' },
    { german: 'Meine Frau ist so groß wie ich.', russian: 'Моя жена такая же высокая, как и я.' },
    { german: 'Wie soll ich das machen?', russian: 'Как мне это сделать?' },
    { german: 'Wie groß ist die Wohnung?', russian: 'Какова площадь квартиры?' },
    { german: 'Wie bitte?', russian: 'Что, извините?' },
    { german: 'Wie lange bist du schon hier?', russian: 'Сколько времени ты уже здесь?' },
    { german: 'Können Sie das bitte wiederholen?', russian: 'Можете повторить, пожалуйста?' },
    { german: 'Wir müssen jetzt Schluss machen. Also auf Wiederhören!', russian: 'Нам нужно закончить. До свидания, так что на слух!' },
    { german: 'Auf Wiedersehen!', russian: 'До свидания!' },
    { german: 'Wie viel Milch nehmen Sie?', russian: 'Сколько молока вы возьмете?' },
    { german: 'Herzlich willkommen!', russian: 'Добро пожаловать!' },
    { german: 'Der Wind kommt aus Osten.', russian: 'Ветер дует с востока.' },
    { german: 'Wir lernen Deutsch.', russian: 'Мы учим немецкий.' },
    { german: 'Weißt du, wie er heißt?', russian: 'Знаешь ли ты, как его зовут?' },
    { german: 'Wo waren Sie im Urlaub?', russian: 'Где вы были в отпуске?' },
    { german: 'Wo ist die Post?', russian: 'Где почта?' },
    { german: 'Wo sind Sie geboren?', russian: 'Где вы родились?' },
    { german: 'Woher kommen Sie?', russian: 'Откуда вы?' },
    { german: 'Wohin fährt dieser Bus?', russian: 'Куда идет этот автобус?' },
    { german: 'Wohin wollen Sie am Wochenende?', russian: 'Куда вы собираетесь на выходных?' },
    { german: 'Ich wohne in München.', russian: 'Я живу в Мюнхене.' },
    { german: 'Seit wann haben Sie diese Wohnung?', russian: 'С какого времени у вас эта квартира?' },
    { german: 'Wollen Sie einen Kaffee trinken?', russian: 'Вы хотите выпить кофе?' },
    { german: 'Ich kenne das Wort nicht.', russian: 'Я не знаю это слово.' },
    { german: 'Das Essen schmeckt wunderbar.', russian: 'Еда прекрасно вкусная.' }
  ];

  const words23 = [
    { german: 'Zahlen, bitte!', russian: 'Счет, пожалуйста!' },
    { german: 'Ich habe heute keine Zeit.', russian: 'Сегодня у меня нет времени.' },
    { german: 'Zurzeit habe ich sehr viel zu tun.', russian: 'Сейчас у меня очень много дел.' },
    { german: 'Ich lese gern Zeitung.', russian: 'Я с удовольствием читаю газету.' },
    { german: 'Wie teuer sind die Zigaretten?', russian: 'Сколько стоят сигареты?' },
    { german: 'Das Zimmer ist groß.', russian: 'Комната большая.' },
    { german: 'Öffne im Schlafzimmer das Fenster, bitte!', russian: 'Открой окно в спальне, пожалуйста!' },
    { german: 'Die Wohnung hat drei Zimmer.', russian: 'В квартире три комнаты.' },
    { german: 'Ich habe ein Zimmer bestellt.', russian: 'Я заказал комнату.' },
    { german: 'Wir müssen noch durch den Zoll.', russian: 'Мы еще должны пройти через таможню.' },
    { german: 'Der Bus fährt zum Bahnhof.', russian: 'Автобус едет на вокзал.' },
    { german: 'Ich gehe zu Fuß.', russian: 'Я иду пешком.' },
    { german: 'Ich bin zu Hause.', russian: 'Я дома.' },
    { german: 'Ich bin mit der Wohnung zufrieden.', russian: 'Я доволен квартирой.' },
    { german: 'Ich fahre gern mit dem Zug.', russian: 'Я люблю ездить на поезде.' },
    { german: 'Einmal Frankfurt und zurück.', russian: 'Туда и обратно до Франкфурта.' },
    { german: 'Wann kommst du zurück?', russian: 'Когда ты вернешься?' },
    { german: 'Sollen wir zusammen essen gehen?', russian: 'Давай пойдем поужинать вместе?' },
    { german: 'Das macht zusammen 2 Euro 80.', russian: 'Это в сумме 2 евро 80 центов.' },
    { german: 'Heidelberg liegt zwischen Frankfurt und Stuttgart.', russian: 'Гейдельберг находится между Франкфуртом и Штутгартом.' },
    { german: 'Zwischen 8 und 10 Uhr bin ich zu Hause.', russian: 'С 8 до 10 часов утра я дома.' }
  ];

  // Объявляем переменную для отслеживания текущего массива слов
  let currentWords = words1;
  
  // Функция для обновления содержимого карточки по ID слова и перевода
  function updateCardContent(frontWordId, backTranslationId, wordsArray) {
    const frontWordElement = document.getElementById(frontWordId);
    const backTranslationElement = document.getElementById(backTranslationId);
  
    // Здесь вы можете использовать вашу логику для выбора случайного слова и перевода из массива
    const randomIndex = Math.floor(Math.random() * wordsArray.length);
    const randomWord = wordsArray[randomIndex];
  
    // Обновляем содержимое карточки с новым словом и переводом
    frontWordElement.innerText = randomWord.german;
    backTranslationElement.innerText = randomWord.russian;
  }
  
  // Вызываем функцию updateCardContent() для каждой карточки чтобы показать первое слово и перевод при загрузке страницы
  updateCardContent('frontWord1', 'backTranslation1', words1);
  updateCardContent('frontWord2', 'backTranslation2', words2);
  updateCardContent('frontWord3', 'backTranslation3', words3);
  updateCardContent('frontWord4', 'backTranslation4', words4);
  updateCardContent('frontWord5', 'backTranslation5', words5);
  updateCardContent('frontWord6', 'backTranslation6', words6);
  updateCardContent('frontWord7', 'backTranslation7', words7);
  updateCardContent('frontWord8', 'backTranslation8', words8);
  updateCardContent('frontWord9', 'backTranslation9', words9);
  updateCardContent('frontWord10', 'backTranslation10', words10);
  updateCardContent('frontWord11', 'backTranslation11', words11);
  updateCardContent('frontWord12', 'backTranslation12', words12);
  updateCardContent('frontWord13', 'backTranslation13', words13);
  updateCardContent('frontWord14', 'backTranslation14', words14);
  updateCardContent('frontWord15', 'backTranslation15', words15);
  updateCardContent('frontWord16', 'backTranslation16', words16);
  updateCardContent('frontWord17', 'backTranslation17', words17);
  updateCardContent('frontWord18', 'backTranslation18', words18);
  updateCardContent('frontWord19', 'backTranslation19', words19);
  updateCardContent('frontWord20', 'backTranslation20', words20);
  updateCardContent('frontWord21', 'backTranslation21', words21);
  updateCardContent('frontWord22', 'backTranslation22', words22);
  updateCardContent('frontWord23', 'backTranslation23', words23);
  
  let isFlipping = false; // Добавляем переменную для отслеживания состояния переворота
  
  // Функция переворота карточки
  function flipCard(frontWordId, backTranslationId, wordsArray) {
    if (isFlipping) return; // Если карточка в процессе переворота, просто выходим
  
    const card = document.getElementById(frontWordId).closest('.card');
    card.classList.toggle('flipped');
    isFlipping = true;
  
    // Добавляем обработчик события окончания анимации переворота
    card.addEventListener('transitionend', function handleTransitionEnd() {
        // После окончания анимации переворота
        if (card.classList.contains('flipped')) {
            updateCardContent(frontWordId, backTranslationId, wordsArray); // Обновляем слово и перевод только после второго клика и переворота в положение "flipped"
        }
        isFlipping = false;
        card.removeEventListener('transitionend', handleTransitionEnd); // Удаляем обработчик события после использования
    });
  }